#!/usr/bin/env bash
# Autonomous Pacman Mirror Orchestrator
# Resolves mirror selection, waits for active pacman locks with a 60s timeout,
# removes stale locks via /proc inspection, runs mirror benchmarking with 
# asynchronous visual feedback, and configures systemd timers.

set -euo pipefail

# --- STRICT ABORT TRAP ---
CURRENT_BG_PID=''
CURRENT_BG_LOG=''

abort_script() {
    printf '\n\033[?25h\033[31m!! User aborted script execution.\033[0m\n' >&2

    if [[ -n ${CURRENT_BG_PID:-} ]] && kill -0 "$CURRENT_BG_PID" 2>/dev/null; then
        kill -TERM -- "-$CURRENT_BG_PID" 2>/dev/null || true

        for _ in {1..20}; do
            kill -0 "$CURRENT_BG_PID" 2>/dev/null || break
            sleep 0.1
        done

        if kill -0 "$CURRENT_BG_PID" 2>/dev/null; then
            kill -KILL -- "-$CURRENT_BG_PID" 2>/dev/null || true
        fi

        wait "$CURRENT_BG_PID" 2>/dev/null || true
    fi

    if [[ -n ${CURRENT_BG_LOG:-} ]]; then
        rm -f -- "$CURRENT_BG_LOG"
    fi

    CURRENT_BG_PID=''
    CURRENT_BG_LOG=''

    exit 1
}

trap abort_script SIGINT SIGTERM

# --- CONFIGURATION ---
readonly PACMAN_LOCK="/var/lib/pacman/db.lck"
readonly TARGET_FILE="/etc/pacman.d/mirrorlist"
readonly REFLECTOR_CONF="/etc/xdg/reflector/reflector.conf"

# --- GLOBAL FALLBACK STORE ---
# Hardcoded to x86_64 to prevent $arch expanding to x86_64_v3 on standard mirrors
read -r -d '' FALLBACK_MIRRORS << 'EOF' || true
## Global CDN Fallback (Auto-generated by orchestrator)
Server = https://geo.mirror.pkgbuild.com/$repo/os/x86_64
Server = https://fastly.mirror.pkgbuild.com/$repo/os/x86_64
Server = https://mirror.rackspace.com/archlinux/$repo/os/x86_64
EOF

# --- COLORS (TTY Conditional) ---
if [[ -t 1 ]]; then
    readonly G=$'\e[32m' R=$'\e[31m' Y=$'\e[33m' B=$'\e[34m' NC=$'\e[0m'
else
    readonly G="" R="" Y="" B="" NC=""
fi

log_info() { printf '%s:: %s%s\n' "$B" "$1" "$NC"; }
log_ok()   { printf '%s:: %s%s\n' "$G" "$1" "$NC"; }
log_warn() { printf '%s:: %s%s\n' "$Y" "$1" "$NC"; }
log_err()  { printf '%s!! %s%s\n' "$R" "$1" "$NC" >&2; }

# --- ATOMIC FILE WRITER ---
write_text_file_atomic() {
    local target="$1"
    local mode="$2"
    local content="$3"
    local tmp rc

    tmp="$(mktemp "${target}.tmp.XXXXXX")"

    if {
        printf '%s\n' "$content" > "$tmp"
        chmod "$mode" "$tmp"
        mv -f -- "$tmp" "$target"
    }; then
        return 0
    fi

    rc=$?
    rm -f -- "$tmp"
    return "$rc"
}

apply_arch_fallback_mirrorlist() {
    write_text_file_atomic "$TARGET_FILE" 0644 "$FALLBACK_MIRRORS"
}

# --- ASYNCHRONOUS UI WRAPPER ---
run_with_spinner() {
    local msg="$1"
    shift

    local tmp_log pid rc
    tmp_log="$(mktemp)"
    CURRENT_BG_LOG=$tmp_log

    setsid -w -- "$@" </dev/null > "$tmp_log" 2>&1 &
    pid=$!
    CURRENT_BG_PID=$pid

    local delay=0.1
    local frames=( '⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏' )

    if [[ -t 1 ]]; then
        printf '\033[?25l'

        while kill -0 "$pid" 2>/dev/null; do
            for frame in "${frames[@]}"; do
                kill -0 "$pid" 2>/dev/null || break
                printf '\r%s::%s %s %s' "$B" "$NC" "$frame" "$msg"
                sleep "$delay"
            done
        done

        printf '\033[?25h\r\033[K'
    fi

    if wait "$pid"; then
        CURRENT_BG_PID=''
        CURRENT_BG_LOG=''
        rm -f -- "$tmp_log"
        return 0
    fi

    rc=$?
    CURRENT_BG_PID=''
    CURRENT_BG_LOG=''

    log_warn "Process encountered issues. Reviewing trace:"
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -n "$line" ]] && log_warn "  -> $line"
    done < "$tmp_log"

    rm -f -- "$tmp_log"
    return "$rc"
}

# --- PRE-FLIGHT ---
if (( EUID != 0 )); then
    if ! command -v sudo &>/dev/null; then
        log_err "This script must be run as root, or sudo must be installed and available."
        exit 1
    fi

    log_info "Elevated privileges required. Prompting for sudo password..."
    exec sudo -- "$0" "$@"
fi

# --- LOCK MANAGEMENT ---
manage_pacman_lock() {
    local -a active_pids=()
    local last_report=''
    local current_report=''
    local elapsed_time=0
    local timeout=60

    while [[ -f "$PACMAN_LOCK" ]]; do
        mapfile -t active_pids < <(
            find /proc/[0-9]*/fd -xtype f -lname "$PACMAN_LOCK" -printf '%h\n' 2>/dev/null |
            awk -F/ '{print $3}' |
            sort -u
        )

        if ((${#active_pids[@]})); then
            current_report="${active_pids[*]}"

            if [[ "$current_report" != "$last_report" ]]; then
                log_warn "Lock file detected at ${PACMAN_LOCK}. Active holder PID(s): ${current_report}. Waiting..."
                last_report="$current_report"
            fi

            if (( elapsed_time >= timeout )); then
                log_warn "Timeout of ${timeout}s reached. Forcibly overriding deadlocked pacman instance..."
                rm -f -- "$PACMAN_LOCK"
                log_ok "Active lock forcibly removed."
                break
            fi

            sleep 2
            (( elapsed_time += 2 ))
            continue
        fi

        log_info "Kernel inspection confirms lock is orphaned (stale). Purging..."
        rm -f -- "$PACMAN_LOCK"
        log_ok "Stale lock safely removed."
        break
    done
}

# --- PACMAN WRAPPER ---
run_pacman() {
    local rc tmp_err

    while :; do
        manage_pacman_lock
        tmp_err="$(mktemp)"

        if LC_ALL=C pacman "$@" 2> "$tmp_err"; then
            rm -f -- "$tmp_err"
            return 0
        fi

        rc=$?

        if [[ -s "$tmp_err" ]]; then
            cat -- "$tmp_err" >&2
        fi

        if grep -Fq 'unable to lock database' "$tmp_err" || \
           grep -Fq 'could not lock database' "$tmp_err"; then
            rm -f -- "$tmp_err"
            log_warn "Pacman reported database lock contention. Waiting for the active transaction to finish..."
            continue
        fi

        rm -f -- "$tmp_err"
        return "$rc"
    done
}

# --- OS DETECTION ---
determine_os_state() {
    # 1. Pure CachyOS - natively manages its own architecture
    if [[ -r /etc/os-release ]] && grep -iq 'cachyos' /etc/os-release; then
        echo "pure_cachyos"
        return 0
    fi
    # 2. Franken-Arch - Standard Arch with CachyOS repos layered on top
    if grep -q '\[cachyos-v3\]' /etc/pacman.conf 2>/dev/null || pacman -Qq cachyos-mirrorlist &>/dev/null; then
        echo "franken_arch"
        return 0
    fi
    # 3. Pure Standard Arch
    echo "arch"
}

# --- CACHYOS KEYRING BOOTSTRAP ---
ensure_cachyos_keyring() {
    if pacman -Qq cachyos-keyring &>/dev/null; then
        log_info "CachyOS keyring already present, skipping bootstrap."
        return 0
    fi

    log_info "CachyOS keyring not found. Bootstrapping..."

    if ! pacman-key --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com; then
        log_warn "Failed to receive CachyOS key from keyserver.ubuntu.com. Trying hkps://keys.openpgp.org..."
        pacman-key --recv-keys F3B607488DB35A47 --keyserver hkps://keys.openpgp.org || {
            log_err "Could not import CachyOS signing key. Mirror sync may fail."
            return 1
        }
    fi

    pacman-key --lsign-key F3B607488DB35A47

    local mirror_base="https://mirror.cachyos.org/repo/x86_64/cachyos"
    
    log_info "Fetching latest keyring package URL..."
    local keyring_pkg
    keyring_pkg=$(curl -sL "${mirror_base}/" | grep -oP 'href="\K(cachyos-keyring-[0-9]+-[0-9]+-any\.pkg\.tar\.zst)' | head -n1 || true)
    
    if [[ -z "$keyring_pkg" ]]; then
        log_warn "Could not scrape dynamic keyring. Falling back to hardcoded version..."
        keyring_pkg="cachyos-keyring-20240331-1-any.pkg.tar.zst"
    fi

    manage_pacman_lock

    if run_pacman -U --needed --noconfirm \
        "${mirror_base}/${keyring_pkg}" \
        "${mirror_base}/cachyos-mirrorlist-27-1-any.pkg.tar.zst" \
        "${mirror_base}/cachyos-v3-mirrorlist-27-1-any.pkg.tar.zst"; then
        log_ok "CachyOS keyring and mirrorlist packages bootstrapped."
    else
        log_warn "Keyring bootstrap failed. Will attempt to continue — cachyos-rate-mirrors may still work."
    fi
}

# --- SYSTEMD TIMER CONFIGURATION ---
configure_arch_timer() {
    log_info "Configuring native systemd timer for automated weekly mirror updates..."

    mkdir -p -- "$(dirname -- "$REFLECTOR_CONF")"

    local reflector_config
    read -r -d '' reflector_config <<EOF || true
--save $TARGET_FILE
--protocol https
--latest 50
--fastest 10
--sort rate
--threads 10
--connection-timeout 2
--download-timeout 2
EOF

    if ! write_text_file_atomic "$REFLECTOR_CONF" 0644 "$reflector_config"; then
        log_warn "Failed to write reflector configuration. Skipping reflector.timer enablement."
        return 0
    fi

    # Standard Arch SHOULD have the timer enabled. 
    # It is only disabled in CachyOS/Franken-Arch configurations.
    if systemctl enable --now reflector.timer &>/dev/null; then
        log_ok "reflector.timer is now active."
    else
        log_warn "Failed to enable reflector.timer. Check systemctl status."
    fi
}

install_persistent_arch_patch() {
    local helper="/usr/local/bin/fix-mirrorlist-arch"

    cat > "$helper" << 'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail
sed -i 's/\$arch_v3/x86_64_v3/g' /etc/pacman.d/cachyos-v3-mirrorlist 2>/dev/null || true
sed -i 's/\$arch/x86_64_v3/g'    /etc/pacman.d/cachyos-v3-mirrorlist 2>/dev/null || true
sed -i 's/\$arch/x86_64/g'       /etc/pacman.d/mirrorlist             2>/dev/null || true
sed -i 's/\$arch/x86_64/g'       /etc/pacman.d/cachyos-mirrorlist     2>/dev/null || true
SCRIPT
    chmod +x "$helper"

    cat > /etc/systemd/system/mirrorlist-arch-patch.service << 'SERVICE'
[Unit]
Description=Fix architecture variables in mirrorlists
Documentation=https://wiki.archlinux.org/title/Pacman

[Service]
Type=oneshot
ExecStartPre=/bin/sleep 1
ExecStart=/usr/local/bin/fix-mirrorlist-arch
SERVICE

    cat > /etc/systemd/system/mirrorlist-arch-patch.path << 'PATH_UNIT'
[Unit]
Description=Monitor mirrorlists and reapply architecture variable fixes
Documentation=https://wiki.archlinux.org/title/Pacman

[Path]
PathChanged=/etc/pacman.d/mirrorlist
PathChanged=/etc/pacman.d/cachyos-mirrorlist
PathChanged=/etc/pacman.d/cachyos-v3-mirrorlist

[Install]
WantedBy=multi-user.target
PATH_UNIT

    systemctl daemon-reload
    systemctl enable --now mirrorlist-arch-patch.path &>/dev/null || true
    log_ok "Persistent arch patch monitor (mirrorlist-arch-patch.path) active."
}

# --- MIRRORLIST ARCHITECTURE PATCHER ---
patch_mirrorlist_architectures() {
    log_info "Hardcoding architectures to prevent pacman variable evaluation bugs..."

    if [[ -f "$TARGET_FILE" ]]; then
        sed -i 's/\$arch/x86_64/g' "$TARGET_FILE"
    fi

    if [[ -f "/etc/pacman.d/cachyos-mirrorlist" ]]; then
        sed -i 's/\$arch/x86_64/g' "/etc/pacman.d/cachyos-mirrorlist"
    fi

    if [[ -f "/etc/pacman.d/cachyos-v3-mirrorlist" ]]; then
        sed -i 's/\$arch_v3/x86_64_v3/g' "/etc/pacman.d/cachyos-v3-mirrorlist"
        sed -i 's/\$arch/x86_64_v3/g' "/etc/pacman.d/cachyos-v3-mirrorlist"
    fi
    log_ok "Architectures successfully patched."

    install_persistent_arch_patch
}

# --- CACHYOS SYNC ---
sync_cachyos() {
    log_info "Initializing Franken-Arch Mirror Sync..."

    ensure_cachyos_keyring

    local attempt
    local max_attempts=3
    local success=0

    if ! command -v cachyos-rate-mirrors &>/dev/null; then
        log_warn "cachyos-rate-mirrors binary missing. Skipping CachyOS mirror ranking and keeping the current mirror configuration."
    else
        for (( attempt = 1; attempt <= max_attempts; attempt++ )); do
            manage_pacman_lock

            if run_with_spinner "Benchmarking CachyOS mirrors..." cachyos-rate-mirrors; then
                success=1
                break
            fi

            if (( attempt < max_attempts )); then
                log_warn "Network latency detected. Retrying in 5 seconds (Attempt $(( attempt + 1 ))/${max_attempts})..."
                sleep 5
            fi
        done

        if (( ! success )); then
            log_err "cachyos-rate-mirrors failed after ${max_attempts} attempts. Continuing with the existing mirror configuration."
        else
            log_ok "CachyOS mirrors optimized."
        fi

        # Disable all native timers in favor of the persistent path unit patcher
        for bad_timer in cachyos-mirrorlist.timer cachyos-rate-mirrors.timer reflector.timer; do
            if systemctl list-unit-files --type=timer --no-legend --plain 2>/dev/null | awk '{print $1}' | grep -Fxq "$bad_timer"; then
                systemctl stop --now "$bad_timer" &>/dev/null || true
                log_warn "Disabled $bad_timer — the persistent path monitor handles repatching."
            fi
        done
    fi

    patch_mirrorlist_architectures

    log_info "Synchronizing pacman databases..."
    run_pacman -Syy || log_warn "Pacman database sync returned non-zero, but pipeline will continue."
}

# --- ARCH LINUX SYNC ---
sync_arch() {
    log_info "Initializing Native Arch Mirror Sync..."

    manage_pacman_lock

    if ! command -v reflector &>/dev/null; then
        log_info "Reflector missing. Bootstrapping dependency..."
        if ! run_pacman -Syu --needed --noconfirm reflector; then
            log_warn "Reflector bootstrap failed with current mirrors."
            log_info "Applying highly-available Global CDN Fallback to recover bootstrap..."
            manage_pacman_lock
            apply_arch_fallback_mirrorlist

            if ! run_pacman -Syu --needed --noconfirm reflector; then
                log_warn "Reflector bootstrap still failed. Continuing with fallback mirrorlist."
            fi
        fi
    fi

    if command -v reflector &>/dev/null; then
        local reflector_tmp
        reflector_tmp="$(mktemp "${TARGET_FILE}.tmp.XXXXXX")"

        manage_pacman_lock

        if run_with_spinner "Benchmarking 50 global mirrors (10 threads)..." \
            reflector --latest 50 \
                      --protocol https \
                      --threads 10 \
                      --connection-timeout 2 \
                      --download-timeout 2 \
                      --fastest 10 \
                      --sort rate \
                      --save "$reflector_tmp"; then
            if {
                chmod 0644 "$reflector_tmp"
                mv -f -- "$reflector_tmp" "$TARGET_FILE"
            }; then
                log_ok "Arch mirrors topologically optimized in parallel."
                configure_arch_timer
            else
                rm -f -- "$reflector_tmp"
                log_warn "Generated mirrorlist could not be installed."
                log_info "Applying highly-available Global CDN Fallback to guarantee pipeline integrity..."
                manage_pacman_lock
                apply_arch_fallback_mirrorlist
                log_ok "Global CDN fallback applied."
            fi
        else
            rm -f -- "$reflector_tmp"
            log_warn "Reflector routing error. Bypassing..."
            log_info "Applying highly-available Global CDN Fallback to guarantee pipeline integrity..."
            manage_pacman_lock
            apply_arch_fallback_mirrorlist
            log_ok "Global CDN fallback applied."
        fi
    else
        log_warn "Reflector remains unavailable after bootstrap. Using highly-available Global CDN fallback."
        manage_pacman_lock
        apply_arch_fallback_mirrorlist
        log_ok "Global CDN fallback applied."
    fi

    # Notice: Patchers are NOT applied here because standard Arch utilizes $arch 
    # natively without conflicts. reflector.timer manages updates organically.

    log_info "Synchronizing pacman databases..."
    run_pacman -Syy || log_warn "Pacman database sync returned non-zero, but pipeline will continue."
}

# --- ENTRY POINT ---
main() {
    printf '\n%s:: Commencing Zero-Interaction Mirror Orchestration%s\n' "$B" "$NC"

    manage_pacman_lock

    local os_state
    os_state="$(determine_os_state)"

    if [[ "$os_state" == "pure_cachyos" ]]; then
        log_info "Pure CachyOS detected. Mirror and timer management is natively handled by the OS. Exiting safely."
        exit 0
    elif [[ "$os_state" == "franken_arch" ]]; then
        sync_cachyos
    else
        sync_arch
    fi

    printf '\n%s:: Orchestration Complete. Yielding execution to next script.%s\n\n' "$G" "$NC"
}

main "$@"
