#!/usr/bin/env bash
#
# Arch Linux mkinitcpio Configuration Optimizer
# Context: Configures mkinitcpio drop-in dynamically based on active topology.
# Target: /etc/mkinitcpio.conf.d/10-arch-btrfs-luks.conf
#

# --- 1. Safety & Environment ---
set -euo pipefail
export LC_ALL=C

# Fail-fast: Ensure root execution
if (( EUID != 0 )); then
    printf "\e[31m[ERROR]\e[0m This script must be run as root.\n" >&2
    exit 1
fi

# --- 2. Visuals & Helpers ---
readonly BOLD=$'\e[1m'
readonly RESET=$'\e[0m'
readonly GREEN=$'\e[32m'
readonly BLUE=$'\e[34m'
readonly RED=$'\e[31m'
readonly YELLOW=$'\e[33m'

log_info() { printf "${BLUE}[INFO]${RESET} %s\n" "$1"; }
log_success() { printf "${GREEN}[SUCCESS]${RESET} %s\n" "$1"; }
log_error() { printf "${RED}[ERROR]${RESET} %s\n" "$1"; }
log_step() { printf "\n${BOLD}${YELLOW}>>> STEP: %s${RESET}\n" "$1"; }

ask_next_step() {
    local step_description="$1"
    printf "\n${BLUE}----------------------------------------------------------------${RESET}\n"
    printf "${BOLD}UPCOMING STEP:${RESET} %s\n" "$step_description"

    if [[ "${INTERACTIVE_MODE:-false}" == "false" ]]; then
        printf "${GREEN}>> Auto-proceeding...${RESET}\n"
        return 0
    fi

    while true; do
        read -r -p "Action: [P]roceed, [S]kip, or [Q]uit? (p/s/q) [Default: p]: " choice
        choice=${choice:-p}
        case "${choice,,}" in
            p|proceed|y|yes) return 0 ;;
            s|skip) log_info "Skipping step: $step_description"; return 1 ;;
            q|quit) log_info "User requested exit."; exit 0 ;;
            *) printf "Invalid choice.\n" ;;
        esac
    done
}

# --- 3. Dependency Validation ---
verify_dependencies() {
    local missing_deps=0

    # Using type -P for strict path resolution in Bash
    if ! type -P btrfs >/dev/null 2>&1; then
        log_error "btrfs-progs is not installed. System dependencies incomplete."
        missing_deps=1
    fi

    if ! type -P cryptsetup >/dev/null 2>&1; then
        log_error "cryptsetup is not installed. System dependencies incomplete."
        missing_deps=1
    fi

    if (( missing_deps > 0 )); then
        log_error "Dependency pre-flight checks failed. Aborting."
        exit 1
    fi
}

# --- 4. Main Logic ---
INTERACTIVE_MODE="${INTERACTIVE_MODE:-false}"

log_step "mkinitcpio.conf Optimization (Topology-Aware Drop-in)"

if ask_next_step "Configure mkinitcpio (Dynamic Block/LUKS/BTRFS mapping)"; then
    
    log_info "Running dependency pre-flight checks..."
    verify_dependencies
    log_success "Dependencies verified."

    log_info "Analyzing filesystem topology for mkinitcpio hooks..."
    RAW_ROOT_MNT=$(findmnt -n -e -o SOURCE -T / | head -n1 || true)
    ROOT_BLK_DEV="${RAW_ROOT_MNT%%\[*}"
    CRYPT_DEV=$(lsblk -nrspo PATH,TYPE -s -- "$ROOT_BLK_DEV" 2>/dev/null | awk '$2 == "crypt" { print $1; exit }' || true)
    ROOT_FSTYPE=$(findmnt -n -e -o FSTYPE -T / | head -n1 || true)

    # --- OPTIMIZED TOPOLOGY ---
    # The MODULES array is deliberately left blank to ensure absolute minimal RAM usage.
    # The 'autodetect' hook combined with the 'kms' hook will dynamically identify 
    # and load ONLY the specific GPU driver required for this hardware.
    MODULES_ARRAY=""
    BINARIES_ARRAY=""
    
    # Modern systemd hook array. 'keyboard' must precede 'autodetect' to ensure
    # USB/external keyboards are included for early LUKS unlocking.
    HOOKS_ARRAY="systemd keyboard autodetect microcode modconf kms sd-vconsole block"

    if [[ -n "$CRYPT_DEV" ]]; then
        log_info "LUKS encryption detected on root device. Injecting 'sd-encrypt'."
        HOOKS_ARRAY="${HOOKS_ARRAY} sd-encrypt"
    else
        log_info "No LUKS layer detected. Skipping 'sd-encrypt' hook."
    fi

    if [[ "$ROOT_FSTYPE" == "btrfs" ]]; then
        log_info "BTRFS root detected. Injecting 'btrfs' module and binaries."
        # If BTRFS is used, we inject ONLY the btrfs module here.
        MODULES_ARRAY="btrfs"
        BINARIES_ARRAY="/usr/bin/btrfs"
    fi

    HOOKS_ARRAY="${HOOKS_ARRAY} filesystems"

    readonly CONF_DIR="/etc/mkinitcpio.conf.d"
    # Keep the original filename for pipeline compatibility
    readonly CONF_FILE="${CONF_DIR}/10-arch-btrfs-luks.conf"

    log_info "Deploying dynamic, hyper-optimized drop-in configuration to $CONF_FILE..."
    
    install -d -m0755 "$CONF_DIR"
    
    cat << EOF > "$CONF_FILE"
# Dynamic Topology Architecture (Ultra-Lean)
# Generated by Arch Orchestrator
MODULES=(${MODULES_ARRAY})
BINARIES=(${BINARIES_ARRAY})
HOOKS=(${HOOKS_ARRAY})
EOF
    
    chmod 0644 "$CONF_FILE"
            
    log_success "Dynamic mkinitcpio drop-in deployed successfully."
    log_info "NOTE: Initramfs generation will occur in a later step."
fi
