#!/usr/bin/env bash
# ==============================================================================
# Hyprland Keybind Manager - System Architect Edition (v2026-Golden)
# ==============================================================================
#
# ARCHITECTURE & SAFETY PROTOCOLS:
# 1. Zero-Subprocess Parsing: Uses Bash mapfile and native ERE regex.
# 2. Intent & Comment Respect: Regex intentionally matches commented-out binds. 
# 3. Symlink Preservation: Resolves canonical paths to prevent Stow/Chezmoi breakage.
# 4. True Metadata Cloning: Uses `cp -pf` to guarantee ACL/Ownership retention.
# 5. Surgical Append: Appends without destructing/reconstructing the source file.
# 6. Atomic Write-Sync-Move: Guarantees zero file corruption.
# 7. Cascading Signal Traps: Ensures deterministic temp file cleanup.
#
# ==============================================================================
# ==============================================================================
# HOW TO ADD NEW KEYBINDS (INSTRUCTION MANUAL)
# ==============================================================================
#
# This script uses an intelligent, intent-based injection matrix. Instead of 
# blindly checking if a specific key combination (like `$mainMod, E`) exists, 
# it searches for the *execution payload*. 
#
# WHY? If a user changes their File Manager bind from 'E' to 'F', but keeps 
# the action 'exec, uwsm-app $fileManager', this script recognizes the action 
# is still bound and will NOT overwrite or duplicate it. 
#
# ------------------------------------------------------------------------------
# THE FORMAT
# ------------------------------------------------------------------------------
# Every new keybind must be added as a single string inside the INJECTIONS 
# array, separated by the pipe delimiter '|'.
#
# Syntax: 'Search_Regex | Header_Comment | Bind_String'
#
# --- FIELD 1: Search_Regex (Bash Extended Regular Expression) ---
# This is the pattern used to scan the file. 
# * It is evaluated purely in-memory.
# * You MUST escape dollar signs (`\$`) so Bash doesn't evaluate them as variables 
#   inside the regex engine.
# * Use `.*` to allow for arbitrary spacing or command flags.
# * IMPORTANT: The regex intentionally matches commented-out lines (e.g., 
#   `# bind = ...`). If a user comments out a bind to disable it, we respect 
#   their intent and do not force-reinject it.
# * ADVANCED: If your target command is a subset of another (e.g., `$terminal` 
#   vs `$terminal -e nvim`), anchor the end of your regex with: 
#   `([[:space:]]*(#.*)?)$` 
#   This ensures it only matches the standalone command, ignoring trailing flags.
#
# --- FIELD 2: Header_Comment ---
# The exact comment string injected one line above the keybind. This keeps the 
# generated config clean and clearly marks auto-generated sections.
# Example: '# Auto-generated by My Custom Switcher'
#
# --- FIELD 3: Bind_String ---
# The actual Hyprland configuration string to inject if the regex fails to find 
# an existing match. Do NOT escape dollar signs here; you want them written 
# literally to the file.
#
# ------------------------------------------------------------------------------
# STEP-BY-STEP EXAMPLE: Adding a System Monitor (btop)
# ------------------------------------------------------------------------------
# Let's say we want to bind: 
# bindd = $mainMod, Escape, Launch Monitor, exec, uwsm-app -- $terminal -e btop
#
# 1. Regex: We want to search for 'exec, uwsm-app -- $terminal -e btop'.
#    Regex string: 'exec,.*\$terminal -e btop'
# 2. Header: '# Auto-generated by Monitor Switcher'
# 3. Bind:   'bindd = $mainMod, Escape, Launch Monitor, exec, uwsm-app -- $terminal -e btop'
#
# Combined Matrix Entry:
# 'exec,.*\$terminal -e btop|# Auto-generated by Monitor Switcher|bindd = $mainMod, Escape, Launch Monitor, exec, uwsm-app -- $terminal -e btop'
# ==============================================================================
#
set -euo pipefail

# --- Configuration ---
readonly TARGET_FILE="${HOME}/.config/hypr/edit_here/source/keybinds.conf"
readonly DELIM='|'

# --- ANSI Constants ---
readonly C_RESET=$'\033[0m'
readonly C_CYAN=$'\033[1;36m'
readonly C_GREEN=$'\033[1;32m'
readonly C_RED=$'\033[1;31m'

log_info()    { printf '%s[INFO]%s %s\n' "$C_CYAN" "$C_RESET" "$1"; }
log_success() { printf '%s[SUCCESS]%s %s\n' "$C_GREEN" "$C_RESET" "$1"; }
log_err()     { printf '%s[ERROR]%s %s\n' "$C_RED" "$C_RESET" "$1" >&2; }

# ------------------------------------------------------------------------------
# INJECTION MATRIX
# Format: "Search_Regex | Header_Comment | Bind_String"
# ------------------------------------------------------------------------------
declare -a INJECTIONS=(
    'exec,.*\$fileManager|# Auto-generated by FM Switcher|bindd = $mainMod, E, File Manager, exec, uwsm-app $fileManager'
    'exec,.*\$browser|# Auto-generated by Browser Switcher|bindd = $mainMod, W, Launch Browser, exec, uwsm-app -- $browser'
    'exec,.*\$textEditor|# Auto-generated by Text Editor Switcher|bindd = $mainMod, R, Open Text Editor, exec, uwsm-app -- $terminal --class nvim -e $textEditor'
    'exec,.*\$terminal([[:space:]]*(#.*)?)$|# Auto-generated by Terminal Switcher|bindd = $mainMod, Q, Launch Terminal, exec, uwsm-app -- $terminal'
)

# ------------------------------------------------------------------------------
# CORE LOGIC
# ------------------------------------------------------------------------------

main() {
    # 1. Path Resolution (Symlink / Dotfile Manager Safety)
    local actual_target="$TARGET_FILE"
    if [[ -L "$TARGET_FILE" ]]; then
        # -m ensures it resolves safely even if the final file doesn't exist yet
        actual_target=$(realpath -m "$TARGET_FILE")
        log_info "Symlink detected. Operating on true target: $actual_target"
    fi

    local target_dir="${actual_target%/*}"
    [[ -d "$target_dir" ]] || mkdir -p "$target_dir"
    [[ -f "$actual_target" ]] || touch "$actual_target"

    # 2. Load entire file into memory instantly (Read Phase Only)
    local lines=()
    mapfile -t lines < "$actual_target"

    # Pure Bash in-memory evaluation
    pattern_exists() {
        local pattern="$1"
        local line
        for line in "${lines[@]}"; do
            if [[ "$line" =~ $pattern ]]; then
                return 0
            fi
        done
        return 1
    }

    local output_buffer=()
    local additions=0
    local regex header bind item

    # 3. Evaluate Matrix
    for item in "${INJECTIONS[@]}"; do
        IFS="$DELIM" read -r regex header bind <<< "$item"
        
        if ! pattern_exists "$regex"; then
            # Inject a blank line separator if appending to existing content
            if (( ${#lines[@]} > 0 || additions > 0 )); then
                output_buffer+=("")
            fi
            output_buffer+=("$header" "$bind")
            # Pre-increment prevents evaluation to 0, avoiding set -e termination
            ((++additions))
        fi
    done

    # 4. Atomic Write Execution
    if (( additions > 0 )); then
        local tmp_file
        tmp_file=$(mktemp "${target_dir}/.${actual_target##*/}.tmp.XXXXXX") || {
            log_err "Failed to create temporary file."
            exit 1
        }
        
        # Proper Signal Cascading: Evaluated immediately via double quotes
        trap "[[ -f \"$tmp_file\" ]] && rm -f \"$tmp_file\"" EXIT
        trap 'exit 129' HUP
        trap 'exit 130' INT
        trap 'exit 143' TERM

        # Perfectly clone all metadata and original content (bypassing aliases)
        command cp -pf "$actual_target" "$tmp_file"

        # Surgical newline padding: If file has content but lacks a trailing newline, pad it
        if [[ -s "$tmp_file" ]] && [[ -n "$(tail -c 1 "$tmp_file" | tr -d '\n')" ]]; then
            printf "\n" >> "$tmp_file"
        fi

        # Pure Bash Append: Safely append the output buffer to the temp file
        if ! printf "%s\n" "${output_buffer[@]}" >> "$tmp_file"; then
            log_err "I/O failure during buffer flush."
            exit 1
        fi

        # Flush buffer to physical disk, then atomically replace original file
        if ! { sync "$tmp_file" && command mv -f "$tmp_file" "$actual_target"; }; then
            log_err "Atomic write failed during physical sync or mv operation."
            exit 1
        fi

        log_success "Injected $additions missing keybind(s) into ${actual_target}"
    else
        log_info "All configured bindings exist. Integrity verified."
    fi
}

main "$@"
