#!/usr/bin/env python3
"""
===============================================================================
DUSKY TUI: MASTER CONFIGURATION SCHEMA
===============================================================================
Target: ~/.config/hypr/edit_here/source/appearance.lua
Engine: lua
"""

from python.frontend.core_types import ConfigItem

# =============================================================================
# 1. CORE APPLICATION ROUTING
# =============================================================================
ENGINE_TYPE = "lua"
TARGET_FILE = "~/.config/hypr/edit_here/source/appearance.lua"
APP_TITLE = "Appearance Settings"

# =============================================================================
# 2. UI & ENVIRONMENT BEHAVIOR
# =============================================================================
DEFAULT_MODE = "auto"
THEME_FILE = "~/.config/matugen/generated/dusky_tui.json"

# =============================================================================
# 3. TABS DEFINITION
# =============================================================================
TABS = [
    "Presets",
    "Layout",
    "Colors",
    "Interactions",
    "Styling",
    "Effects",
    "Smart",
    "Special"
]

# =============================================================================
# COLOR ALIASES
# =============================================================================
COLOR_ALIASES = [
    # Matugen dynamic variables
    "primary", "secondary", "tertiary", "error", "background", 
    "surface", "surface_variant", "outline", "inverse_on_surface", 
    "on_surface", "primary_container", "secondary_container", "tertiary_container",
    
    # Core system transparencies
    "rgba(1a1a1aee)", "rgba(ffffff11)", "rgba(00000000)",
    
    # Hardcoded base options translated to Hyprland-compliant RGBA strings
    "rgba(ff0000ff)", # Red
    "rgba(00ff00ff)", # Green
    "rgba(0000ffff)", # Blue
    "rgba(ffa500ff)", # Orange
    "rgba(ffff00ff)", # Yellow
    "rgba(800080ff)", # Purple
    "rgba(00ffffff)", # Cyan
    "rgba(ffd700ff)", # Golden
    "rgba(000000ff)", # Black
    "rgba(ffffffff)", # White
    "rgba(ffc0cbff)", # Pink
    "rgba(808080ff)"  # Gray
]

# =============================================================================
# 4. SCHEMA DEFINITION
# =============================================================================
SCHEMA = {
    # -------------------------------------------------------------------------
    # TAB 0: PRESETS
    # -------------------------------------------------------------------------
    0: [
        ConfigItem(
            label="Reset Dusky Defaults",
            key="preset_factory_reset",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Reset",
            preset_payload={"__ALL_DEFAULTS__": True},
            extended_help="**Reset Dusky Defaults**\n\nReverts every single configuration item across all tabs back to its programmed default state."
        ),
        ConfigItem(
            label="Paper Texture",
            key="pre_paper_texture",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 1,
                "general.gaps_in": 6,
                "general.gaps_out": 10,
                "general.float_gaps": 0,
                "general.gaps_workspaces": 0,
                "general.col.active_border": "outline",
                "general.col.inactive_border": "inverse_on_surface",
                "general.col.nogroup_border_active": "secondary",
                "general.col.nogroup_border": "inverse_on_surface",
                "general.resize_on_border": True,
                "general.extend_border_grab_area": 15,
                "general.hover_icon_on_border": True,
                "general.resize_corner": 0,
                "general.allow_tearing": True,
                "decoration.rounding": 0,
                "decoration.rounding_power": 1.0,
                "decoration.border_part_of_window": True,
                "decoration.active_opacity": 0.8,
                "decoration.inactive_opacity": 0.8,
                "decoration.fullscreen_opacity": 0.9,
                "decoration.screen_shader": "",
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.3,
                "decoration.dim_special": 0.8,
                "decoration.dim_around": 0.4,
                "decoration.dim_modal": True,
                "decoration/blur.enabled": True,
                "decoration/blur.size": 3,
                "decoration/blur.passes": 3,
                "decoration/blur.ignore_opacity": True,
                "decoration/blur.new_optimizations": True,
                "decoration/blur.xray": False,
                "decoration/blur.noise": 0.6717,
                "decoration/blur.contrast": 1.6916,
                "decoration/blur.brightness": 2.0,
                "decoration/blur.vibrancy": 0.55,
                "decoration/blur.vibrancy_darkness": 1.0,
                "decoration/blur.special": False,
                "decoration/blur.popups": False,
                "decoration/blur.popups_ignorealpha": 0.2,
                "decoration/blur.input_methods": False,
                "decoration/blur.input_methods_ignorealpha": 0.2,
                "decoration/shadow.enabled": True,
                "decoration/shadow.range": 6,
                "decoration/shadow.render_power": 1,
                "decoration/shadow.sharp": False,
                "decoration/shadow.color": "background",
                "decoration/shadow.scale": 1.0,
                "decoration/glow.enabled": True,
                "decoration/glow.range": 10,
                "decoration/glow.render_power": 3,
                "decoration/glow.color": "primary_container",
                "workspace_rule/w[tv1]s[false].border_size": 1,
                "workspace_rule/w[tv1]s[false].gaps_in": 4,
                "workspace_rule/w[tv1]s[false].gaps_out": 8,
                "window_rule/single_window_style.rounding": 10,
                "window_rule/single_window_style.rounding_power": 2.5,
                "window_rule/single_window_style.opacity": 0.85,
                "window_rule/single_window_style.no_blur": False,
                "workspace_rule/f[1]s[false].border_size": 1,
                "workspace_rule/f[1]s[false].gaps_in": 4,
                "workspace_rule/f[1]s[false].gaps_out": 8,
                "window_rule/maximized_window_style.rounding": 10,
                "window_rule/maximized_window_style.opacity": 0.45,
                "window_rule/maximized_window_style.no_blur": True
            },
            extended_help="**Paper Texture**\n\nApplies highly textured noise and contrasting blur parameters to emulate the physical grit of a paper surface beneath transparent windows."
        ),
        ConfigItem(
            label="Smooth Blur",
            key="pre_smooth_blur",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 1,
                "general.gaps_in": 4,
                "general.gaps_out": 6,
                "general.float_gaps": 0,
                "general.gaps_workspaces": 0,
                "general.col.active_border": "primary",
                "general.col.inactive_border": "inverse_on_surface",
                "general.col.nogroup_border_active": "secondary",
                "general.col.nogroup_border": "inverse_on_surface",
                "general.resize_on_border": True,
                "general.extend_border_grab_area": 15,
                "general.hover_icon_on_border": True,
                "general.resize_corner": 0,
                "general.allow_tearing": True,
                "decoration.rounding": 6,
                "decoration.rounding_power": 2.0,
                "decoration.border_part_of_window": True,
                "decoration.active_opacity": 0.85,
                "decoration.inactive_opacity": 0.85,
                "decoration.fullscreen_opacity": 0.85,
                "decoration.screen_shader": "",
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.1,
                "decoration.dim_around": 0.2,
                "decoration.dim_modal": True,
                "decoration/blur.enabled": True,
                "decoration/blur.size": 4,
                "decoration/blur.passes": 3,
                "decoration/blur.ignore_opacity": True,
                "decoration/blur.new_optimizations": True,
                "decoration/blur.xray": False,
                "decoration/blur.noise": 0.0117,
                "decoration/blur.contrast": 0.8916,
                "decoration/blur.brightness": 1.6,
                "decoration/blur.vibrancy": 1.0,
                "decoration/blur.vibrancy_darkness": 0.25,
                "decoration/blur.popups": False,
                "decoration/blur.popups_ignorealpha": 0.2,
                "decoration/blur.input_methods": False,
                "decoration/blur.input_methods_ignorealpha": 0.2,
                "decoration/shadow.enabled": True,
                "decoration/shadow.range": 10,
                "decoration/shadow.render_power": 1,
                "decoration/shadow.sharp": False,
                "decoration/shadow.color": "rgba(1a1a1aee)",
                "decoration/shadow.scale": 1.0,
                "decoration/glow.enabled": False,
                "decoration/glow.range": 10,
                "decoration/glow.render_power": 3,
                "decoration/glow.color": "primary_container",
                "workspace_rule/w[tv1]s[false].border_size": 1,
                "workspace_rule/w[tv1]s[false].gaps_in": 2,
                "workspace_rule/w[tv1]s[false].gaps_out": 3,
                "window_rule/single_window_style.rounding": 0,
                "window_rule/single_window_style.rounding_power": 1.0,
                "window_rule/single_window_style.opacity": 1.0,
                "window_rule/single_window_style.no_blur": False,
                "workspace_rule/f[1]s[false].border_size": 1,
                "workspace_rule/f[1]s[false].gaps_in": 2,
                "workspace_rule/f[1]s[false].gaps_out": 2,
                "window_rule/maximized_window_style.rounding": 0,
                "window_rule/maximized_window_style.opacity": 1.0,
                "window_rule/maximized_window_style.no_blur": True,
                "decoration.dim_special": 0.8,
                "decoration/blur.special": False,
                "workspace_rule/special:magic.border_size": 3,
                "workspace_rule/special:magic.gaps_in": 4,
                "workspace_rule/special:magic.gaps_out": 20,
                "window_rule/special_magic_style.border_color": "outline",
                "window_rule/special_magic_style.rounding": 6,
                "window_rule/special_magic_style.rounding_power": 2.0,
                "window_rule/special_magic_style.opacity": 0.92,
                "window_rule/special_magic_style.no_blur": True
            },
            extended_help="**Smooth Blur**\n\nApplies the default settings framework, combining smooth blurring algorithms with standard layout values."
        ),
        ConfigItem(
            label="Office Work",
            key="pre_office_work",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 1,
                "general.gaps_in": 2,
                "general.gaps_out": 2,
                "general.float_gaps": 0,
                "general.gaps_workspaces": 0,
                "general.col.active_border": "primary",
                "general.col.inactive_border": "inverse_on_surface",
                "general.col.nogroup_border_active": "secondary",
                "general.col.nogroup_border": "inverse_on_surface",
                "general.resize_on_border": True,
                "general.extend_border_grab_area": 15,
                "general.hover_icon_on_border": True,
                "general.resize_corner": 0,
                "general.allow_tearing": True,
                "decoration.rounding": 0,
                "decoration.rounding_power": 1.0,
                "decoration.border_part_of_window": True,
                "decoration.active_opacity": 1.0,
                "decoration.inactive_opacity": 1.0,
                "decoration.fullscreen_opacity": 1.0,
                "decoration.screen_shader": "",
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.3,
                "decoration.dim_special": 0.8,
                "decoration.dim_around": 0.4,
                "decoration.dim_modal": True,
                "decoration/blur.enabled": False,
                "decoration/blur.size": 10,
                "decoration/blur.passes": 2,
                "decoration/blur.ignore_opacity": True,
                "decoration/blur.new_optimizations": True,
                "decoration/blur.xray": False,
                "decoration/blur.noise": 0.0117,
                "decoration/blur.contrast": 0.8916,
                "decoration/blur.brightness": 0.8172,
                "decoration/blur.vibrancy": 0.1696,
                "decoration/blur.vibrancy_darkness": 0.0,
                "decoration/blur.special": False,
                "decoration/blur.popups": False,
                "decoration/blur.popups_ignorealpha": 0.2,
                "decoration/blur.input_methods": False,
                "decoration/blur.input_methods_ignorealpha": 0.2,
                "decoration/shadow.enabled": False,
                "decoration/shadow.range": 10,
                "decoration/shadow.render_power": 1,
                "decoration/shadow.sharp": False,
                "decoration/shadow.color": "rgba(1a1a1aee)",
                "decoration/shadow.scale": 1.0,
                "decoration/glow.enabled": False,
                "decoration/glow.range": 10,
                "decoration/glow.render_power": 3,
                "decoration/glow.color": "primary_container",
                "workspace_rule/w[tv1]s[false].border_size": 1,
                "workspace_rule/w[tv1]s[false].gaps_in": 2,
                "workspace_rule/w[tv1]s[false].gaps_out": 3,
                "window_rule/single_window_style.rounding": 0,
                "window_rule/single_window_style.rounding_power": 1.0,
                "window_rule/single_window_style.opacity": 1.0,
                "window_rule/single_window_style.no_blur": False,
                "workspace_rule/f[1]s[false].border_size": 1,
                "workspace_rule/f[1]s[false].gaps_in": 2,
                "workspace_rule/f[1]s[false].gaps_out": 2,
                "window_rule/maximized_window_style.rounding": 0,
                "window_rule/maximized_window_style.opacity": 1.0,
                "window_rule/maximized_window_style.no_blur": True
            },
            extended_help="**Office Work**\n\nA solid, distraction-free environment meant for productivity. Enforces tight gaps, disables transparency and blurring effects, and implements strict sharp corners to maximize clear layout structure."
        ),
        ConfigItem(
            label="Retro Noise",
            key="pre_retro_noise",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 1,
                "general.gaps_in": 4,
                "general.gaps_out": 8,
                "general.float_gaps": 0,
                "general.gaps_workspaces": 0,
                "general.col.active_border": "primary",
                "general.col.inactive_border": "inverse_on_surface",
                "general.col.nogroup_border_active": "secondary",
                "general.col.nogroup_border": "inverse_on_surface",
                "general.resize_on_border": True,
                "general.extend_border_grab_area": 15,
                "general.hover_icon_on_border": True,
                "general.resize_corner": 0,
                "general.allow_tearing": True,
                "decoration.rounding": 10,
                "decoration.rounding_power": 2.5,
                "decoration.border_part_of_window": True,
                "decoration.active_opacity": 0.85,
                "decoration.inactive_opacity": 0.85,
                "decoration.fullscreen_opacity": 1.0,
                "decoration.screen_shader": "",
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.3,
                "decoration.dim_special": 0.8,
                "decoration.dim_around": 0.4,
                "decoration.dim_modal": True,
                "decoration/blur.enabled": True,
                "decoration/blur.size": 10,
                "decoration/blur.passes": 2,
                "decoration/blur.ignore_opacity": True,
                "decoration/blur.new_optimizations": True,
                "decoration/blur.xray": False,
                "decoration/blur.noise": 1.0,
                "decoration/blur.contrast": 1.1,
                "decoration/blur.brightness": 2.0,
                "decoration/blur.vibrancy": 1.0,
                "decoration/blur.vibrancy_darkness": 1.0,
                "decoration/blur.special": False,
                "decoration/blur.popups": False,
                "decoration/blur.popups_ignorealpha": 0.2,
                "decoration/blur.input_methods": False,
                "decoration/blur.input_methods_ignorealpha": 0.2,
                "decoration/shadow.enabled": True,
                "decoration/shadow.range": 10,
                "decoration/shadow.render_power": 1,
                "decoration/shadow.sharp": False,
                "decoration/shadow.color": "rgba(1a1a1aee)",
                "decoration/shadow.scale": 1.0,
                "decoration/glow.enabled": False,
                "decoration/glow.range": 10,
                "decoration/glow.render_power": 3,
                "decoration/glow.color": "primary_container",
                "workspace_rule/w[tv1]s[false].border_size": 1,
                "workspace_rule/w[tv1]s[false].gaps_in": 4,
                "workspace_rule/w[tv1]s[false].gaps_out": 8,
                "window_rule/single_window_style.rounding": 10,
                "window_rule/single_window_style.rounding_power": 2.5,
                "window_rule/single_window_style.opacity": 0.85,
                "window_rule/single_window_style.no_blur": False,
                "workspace_rule/f[1]s[false].border_size": 1,
                "workspace_rule/f[1]s[false].gaps_in": 4,
                "workspace_rule/f[1]s[false].gaps_out": 8,
                "window_rule/maximized_window_style.rounding": 10,
                "window_rule/maximized_window_style.opacity": 0.45,
                "window_rule/maximized_window_style.no_blur": True
            },
            extended_help="**Retro Noise**\n\nForces blur noise, brightness, and vibrancy levels to their absolute maximum, producing an intense, highly saturated CRT distortion effect on all transparent surfaces."
        ),
        ConfigItem(
            label="Translucent Air",
            key="pre_translucent_air",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 0,
                "general.gaps_in": 4,
                "general.gaps_out": 10,
                "general.float_gaps": 0,
                "general.gaps_workspaces": 0,
                "general.col.active_border": "primary",
                "general.col.inactive_border": "inverse_on_surface",
                "general.col.nogroup_border_active": "secondary",
                "general.col.nogroup_border": "inverse_on_surface",
                "general.resize_on_border": True,
                "general.extend_border_grab_area": 15,
                "general.hover_icon_on_border": True,
                "general.resize_corner": 0,
                "general.allow_tearing": True,
                "decoration.rounding": 26,
                "decoration.rounding_power": 1.0,
                "decoration.border_part_of_window": True,
                "decoration.active_opacity": 0.95,
                "decoration.inactive_opacity": 0.85,
                "decoration.fullscreen_opacity": 1.0,
                "decoration.screen_shader": "",
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.3,
                "decoration.dim_special": 0.0,
                "decoration.dim_around": 0.4,
                "decoration.dim_modal": True,
                "decoration/blur.enabled": False,
                "decoration/blur.size": 1,
                "decoration/blur.passes": 1,
                "decoration/blur.ignore_opacity": True,
                "decoration/blur.new_optimizations": True,
                "decoration/blur.xray": False,
                "decoration/blur.noise": 0.0117,
                "decoration/blur.contrast": 0.8916,
                "decoration/blur.brightness": 0.8172,
                "decoration/blur.vibrancy": 0.1696,
                "decoration/blur.vibrancy_darkness": 0.0,
                "decoration/blur.special": False,
                "decoration/blur.popups": False,
                "decoration/blur.popups_ignorealpha": 0.2,
                "decoration/blur.input_methods": False,
                "decoration/blur.input_methods_ignorealpha": 0.2,
                "decoration/shadow.enabled": True,
                "decoration/shadow.range": 4,
                "decoration/shadow.render_power": 1,
                "decoration/shadow.sharp": False,
                "decoration/shadow.color": "rgba(1a1a1aee)",
                "decoration/shadow.scale": 1.0,
                "decoration/glow.enabled": False,
                "decoration/glow.range": 10,
                "decoration/glow.render_power": 3,
                "decoration/glow.color": "primary_container",
                "workspace_rule/w[tv1]s[false].border_size": 0,
                "workspace_rule/w[tv1]s[false].gaps_in": 4,
                "workspace_rule/w[tv1]s[false].gaps_out": 12,
                "window_rule/single_window_style.rounding": 20,
                "window_rule/single_window_style.rounding_power": 1.0,
                "window_rule/single_window_style.opacity": 0.85,
                "window_rule/single_window_style.no_blur": False,
                "workspace_rule/f[1]s[false].border_size": 1,
                "workspace_rule/f[1]s[false].gaps_in": 4,
                "workspace_rule/f[1]s[false].gaps_out": 1,
                "window_rule/maximized_window_style.rounding": 10,
                "window_rule/maximized_window_style.opacity": 0.45,
                "window_rule/maximized_window_style.no_blur": True
            },
            extended_help="**Translucent Air**\n\nA very lightweight preset. Turns off heavy blur operations entirely, implements soft rounded corners with no hard borders, and offers an airy and minimal look."
        ),
        ConfigItem(
            label="Packed Room",
            key="pre_packed_room",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 0,
                "general.gaps_in": 1,
                "general.gaps_out": 0,
                "general.float_gaps": 0,
                "general.gaps_workspaces": 0,
                "general.col.active_border": "primary",
                "general.col.inactive_border": "inverse_on_surface",
                "general.col.nogroup_border_active": "secondary",
                "general.col.nogroup_border": "inverse_on_surface",
                "general.resize_on_border": True,
                "general.extend_border_grab_area": 15,
                "general.hover_icon_on_border": True,
                "general.resize_corner": 0,
                "general.allow_tearing": True,
                "decoration.rounding": 0,
                "decoration.rounding_power": 1.0,
                "decoration.border_part_of_window": True,
                "decoration.active_opacity": 0.9,
                "decoration.inactive_opacity": 0.9,
                "decoration.fullscreen_opacity": 1.0,
                "decoration.screen_shader": "",
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.3,
                "decoration.dim_special": 0.0,
                "decoration.dim_around": 0.0,
                "decoration.dim_modal": True,
                "decoration/blur.enabled": True,
                "decoration/blur.size": 1,
                "decoration/blur.passes": 1,
                "decoration/blur.ignore_opacity": True,
                "decoration/blur.new_optimizations": True,
                "decoration/blur.xray": False,
                "decoration/blur.noise": 0.0117,
                "decoration/blur.contrast": 2.0,
                "decoration/blur.brightness": 1.0,
                "decoration/blur.vibrancy": 0.1696,
                "decoration/blur.vibrancy_darkness": 1.0,
                "decoration/blur.special": False,
                "decoration/blur.popups": False,
                "decoration/blur.popups_ignorealpha": 0.2,
                "decoration/blur.input_methods": False,
                "decoration/blur.input_methods_ignorealpha": 0.2,
                "decoration/shadow.enabled": False,
                "decoration/shadow.range": 10,
                "decoration/shadow.render_power": 1,
                "decoration/shadow.sharp": False,
                "decoration/shadow.color": "rgba(1a1a1aee)",
                "decoration/shadow.scale": 1.0,
                "decoration/glow.enabled": False,
                "decoration/glow.range": 10,
                "decoration/glow.render_power": 3,
                "decoration/glow.color": "primary_container",
                "workspace_rule/w[tv1]s[false].border_size": 0,
                "workspace_rule/w[tv1]s[false].gaps_in": 0,
                "workspace_rule/w[tv1]s[false].gaps_out": 0,
                "window_rule/single_window_style.rounding": 0,
                "window_rule/single_window_style.rounding_power": 1.0,
                "window_rule/single_window_style.opacity": 0.85,
                "window_rule/single_window_style.no_blur": False,
                "workspace_rule/f[1]s[false].border_size": 1,
                "workspace_rule/f[1]s[false].gaps_in": 0,
                "workspace_rule/f[1]s[false].gaps_out": 0,
                "window_rule/maximized_window_style.rounding": 0,
                "window_rule/maximized_window_style.opacity": 0.45,
                "window_rule/maximized_window_style.no_blur": True
            },
            extended_help="**Packed Room**\n\nDisables borders, limits gaps to near-zero, entirely drops drop shadows, and sharpens all corners. Maximum screen efficiency for heavy workflow environments."
        ),
        ConfigItem(
            label="Tinted Glass",
            key="pre_tinted_glass",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 1,
                "general.gaps_in": 0,
                "general.gaps_out": 0,
                "general.float_gaps": 0,
                "general.gaps_workspaces": 0,
                "general.col.active_border": "primary",
                "general.col.inactive_border": "inverse_on_surface",
                "general.col.nogroup_border_active": "secondary",
                "general.col.nogroup_border": "inverse_on_surface",
                "general.resize_on_border": True,
                "general.extend_border_grab_area": 15,
                "general.hover_icon_on_border": True,
                "general.resize_corner": 0,
                "general.allow_tearing": True,
                "decoration.rounding": 0,
                "decoration.rounding_power": 1.0,
                "decoration.border_part_of_window": True,
                "decoration.active_opacity": 0.9,
                "decoration.inactive_opacity": 0.9,
                "decoration.fullscreen_opacity": 1.0,
                "decoration.screen_shader": "",
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.3,
                "decoration.dim_special": 0.0,
                "decoration.dim_around": 0.0,
                "decoration.dim_modal": True,
                "decoration/blur.enabled": True,
                "decoration/blur.size": 1,
                "decoration/blur.passes": 1,
                "decoration/blur.ignore_opacity": True,
                "decoration/blur.new_optimizations": True,
                "decoration/blur.xray": False,
                "decoration/blur.noise": 0.0117,
                "decoration/blur.contrast": 2.0,
                "decoration/blur.brightness": 1.0,
                "decoration/blur.vibrancy": 0.1696,
                "decoration/blur.vibrancy_darkness": 1.0,
                "decoration/blur.special": False,
                "decoration/blur.popups": False,
                "decoration/blur.popups_ignorealpha": 0.2,
                "decoration/blur.input_methods": False,
                "decoration/blur.input_methods_ignorealpha": 0.2,
                "decoration/shadow.enabled": False,
                "decoration/shadow.range": 10,
                "decoration/shadow.render_power": 1,
                "decoration/shadow.sharp": False,
                "decoration/shadow.color": "rgba(1a1a1aee)",
                "decoration/shadow.scale": 1.0,
                "decoration/glow.enabled": False,
                "decoration/glow.range": 10,
                "decoration/glow.render_power": 3,
                "decoration/glow.color": "primary_container",
                "workspace_rule/w[tv1]s[false].border_size": 0,
                "workspace_rule/w[tv1]s[false].gaps_in": 0,
                "workspace_rule/w[tv1]s[false].gaps_out": 0,
                "window_rule/single_window_style.rounding": 0,
                "window_rule/single_window_style.rounding_power": 1.0,
                "window_rule/single_window_style.opacity": 0.85,
                "window_rule/single_window_style.no_blur": False,
                "workspace_rule/f[1]s[false].border_size": 1,
                "workspace_rule/f[1]s[false].gaps_in": 0,
                "workspace_rule/f[1]s[false].gaps_out": 0,
                "window_rule/maximized_window_style.rounding": 0,
                "window_rule/maximized_window_style.opacity": 0.45,
                "window_rule/maximized_window_style.no_blur": True
            },
            extended_help="**Tinted Glass**\n\nCreates a flat, sharp-cornered setup combined with high contrast, heavily darkened vibrancy, and no drop shadows. Replicates the sleek look of modern tinted panels."
        ),
        ConfigItem(
            label="Glassmorphism",
            key="pre_glass",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "decoration.active_opacity": 0.75,
                "decoration.inactive_opacity": 0.65,
                "decoration/blur.passes": 3,
                "decoration/blur.size": 15,
                "general.border_size": 0,
                "decoration.rounding": 12,
                "decoration/shadow.enabled": True,
                "decoration/shadow.range": 30
            },
            extended_help="**Glassmorphism Profile**\n\nDeploys heavy transparency combined with intense background blur and soft drop shadows to emulate macOS-style frosted glass environments."
        ),
        ConfigItem(
            label="Elegant Blur",
            key="pre_elegant_blur",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 2,
                "general.gaps_in": 3,
                "general.gaps_out": 6,
                "decoration.rounding": 0,
                "decoration.rounding_power": 1.0,
                "decoration.active_opacity": 0.6,
                "decoration.inactive_opacity": 0.5,
                "decoration.fullscreen_opacity": 0.8,
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.3,
                "decoration/blur.enabled": True,
                "decoration/blur.size": 9,
                "decoration/blur.passes": 3,
                "decoration/shadow.enabled": True,
                "decoration/shadow.range": 6,
                "decoration/shadow.render_power": 1,
                "decoration/shadow.color": "rgba(000000ff)",
                "decoration/shadow.scale": 1.0,
                "decoration/glow.enabled": False
            },
            extended_help="**Elegant Blur**\n\nApplies a configuration with zero rounding, medium borders, tight gaps, and a heavily dimmed inactive workspace with black drop shadows."
        ),
        ConfigItem(
            label="Gamers Euphoria",
            key="pre_gamers_euphoria",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 1,
                "general.gaps_in": 3,
                "general.gaps_out": 6,
                "general.col.active_border": "outline",
                "general.col.inactive_border": "primary_container",
                "decoration.rounding": 28,
                "decoration.rounding_power": 1,
                "decoration.border_part_of_window": True,
                "decoration.active_opacity": 0.8,
                "decoration.inactive_opacity": 0.7,
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.3,
                "decoration/blur.enabled": True,
                "decoration/blur.size": 6,
                "decoration/blur.passes": 3,
                "decoration/blur.contrast": 1.4,
                "decoration/blur.brightness": 0.8,
                "decoration/blur.vibrancy": 1.0,
                "decoration/blur.vibrancy_darkness": 0.6,
                "decoration/shadow.enabled": True,
                "decoration/shadow.range": 4,
                "decoration/shadow.color": "rgba(000000ff)",
                "decoration/glow.enabled": True,
                "decoration/glow.range": 3,
                "decoration/glow.render_power": 1,
                "decoration/glow.color": "primary_container"
            },
            extended_help="**Gamers Euphoria**\n\nA visually immersive preset engineered for gaming setups with intense rounded corners, contrasting outlines, dynamic blur filters, and vibrant neon glow effects."
        ),
        ConfigItem(
            label="Vibrant Soft",
            key="pre_vibrant_soft",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 2,
                "general.gaps_in": 8,
                "general.gaps_out": 14,
                "decoration.rounding": 18,
                "decoration.rounding_power": 1.7,
                "decoration.active_opacity": 0.85,
                "decoration.inactive_opacity": 0.85,
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.3,
                "decoration/blur.enabled": True,
                "decoration/blur.size": 10,
                "decoration/blur.passes": 2,
                "decoration/blur.contrast": 0.5,
                "decoration/blur.brightness": 1.0,
                "decoration/blur.vibrancy": 1.0,
                "decoration/blur.vibrancy_darkness": 0.8,
                "decoration/glow.enabled": False
            },
            extended_help="**Vibrant Soft**\n\nA beautifully soft preset that emphasizes deeply saturated background blurs, wide spacious gaps, and thick corner radiuses for an incredibly clean desktop."
        ),
        ConfigItem(
            label="Aura Farm",
            key="pre_aura_farm",
            scope="DEFAULT",
            type_="preset",
            default=None,
            group="Presets",
            preset_payload={
                "general.border_size": 0,
                "general.gaps_in": 4,
                "general.gaps_out": 6,
                "general.float_gaps": 0,
                "general.gaps_workspaces": 0,
                "general.col.active_border": "primary",
                "general.col.inactive_border": "inverse_on_surface",
                "general.col.nogroup_border_active": "secondary",
                "general.col.nogroup_border": "inverse_on_surface",
                "general.resize_on_border": True,
                "general.extend_border_grab_area": 15,
                "general.hover_icon_on_border": True,
                "general.resize_corner": 0,
                "general.allow_tearing": True,
                "decoration.rounding": 0,
                "decoration.rounding_power": 2.5,
                "decoration.border_part_of_window": True,
                "decoration.active_opacity": 0.85,
                "decoration.inactive_opacity": 0.85,
                "decoration.fullscreen_opacity": 1.0,
                "decoration.screen_shader": "",
                "decoration.dim_inactive": True,
                "decoration.dim_strength": 0.3,
                "decoration.dim_special": 0.8,
                "decoration.dim_around": 0.4,
                "decoration.dim_modal": True,
                "decoration/blur.enabled": True,
                "decoration/blur.size": 6,
                "decoration/blur.passes": 3,
                "decoration/blur.ignore_opacity": True,
                "decoration/blur.new_optimizations": True,
                "decoration/blur.xray": False,
                "decoration/blur.noise": 0.0117,
                "decoration/blur.contrast": 2.0,
                "decoration/blur.brightness": 0.8172,
                "decoration/blur.vibrancy": 1.0,
                "decoration/blur.vibrancy_darkness": 1.0,
                "decoration/blur.special": False,
                "decoration/blur.popups": False,
                "decoration/blur.popups_ignorealpha": 0.2,
                "decoration/blur.input_methods": False,
                "decoration/blur.input_methods_ignorealpha": 0.2,
                "decoration/shadow.enabled": True,
                "decoration/shadow.range": 10,
                "decoration/shadow.render_power": 1,
                "decoration/shadow.sharp": False,
                "decoration/shadow.color": "rgba(1a1a1aee)",
                "decoration/shadow.scale": 1.0,
                "decoration/glow.enabled": True,
                "decoration/glow.range": 10,
                "decoration/glow.render_power": 3,
                "decoration/glow.color": "primary",
                "workspace_rule/w[tv1]s[false].border_size": 0,
                "workspace_rule/w[tv1]s[false].gaps_in": 0,
                "workspace_rule/w[tv1]s[false].gaps_out": 6,
                "window_rule/single_window_style.rounding": 10,
                "window_rule/single_window_style.rounding_power": 2.5,
                "window_rule/single_window_style.opacity": 0.85,
                "window_rule/single_window_style.no_blur": False,
                "workspace_rule/f[1]s[false].border_size": 1,
                "workspace_rule/f[1]s[false].gaps_in": 4,
                "workspace_rule/f[1]s[false].gaps_out": 8,
                "window_rule/maximized_window_style.rounding": 10,
                "window_rule/maximized_window_style.opacity": 0.45,
                "window_rule/maximized_window_style.no_blur": True
            },
            extended_help="**Aura Farm**\n\nA visually striking configuration focusing on high vibrancy, intense contrast, and a distinct primary-colored inner glow. Features zero borders and sharp layout styling."
        ),
    ],

    # -------------------------------------------------------------------------
    # TAB 1: LAYOUT
    # -------------------------------------------------------------------------
    1: [
        ConfigItem(
            label="Border Size",
            key="border_size",
            scope="general",
            type_="int",
            default=2,
            min_val=0,
            max_val=15,
            step=1,
            group="Geometry",
            extended_help="**Border Size**\n\nSets the absolute pixel width of the borders drawn around application windows. Set to 0 to remove borders entirely."
        ),
        ConfigItem(
            label="Gaps In",
            key="gaps_in",
            scope="general",
            type_="int",
            default=3,
            min_val=0,
            max_val=50,
            step=1,
            group="Geometry",
            extended_help="**Inner Gaps**\n\nDefines the spacing (in pixels) between adjacent tiled windows. Higher values create a more spaced-out look."
        ),
        ConfigItem(
            label="Gaps Out",
            key="gaps_out",
            scope="general",
            type_="int",
            default=8,
            min_val=0,
            max_val=50,
            step=1,
            group="Geometry",
            extended_help="**Outer Gaps**\n\nDefines the spacing (in pixels) between windows and the absolute edge of your monitor."
        ),
        ConfigItem(
            label="Float Gaps",
            key="float_gaps",
            scope="general",
            type_="int",
            default=2,
            min_val=-1,
            max_val=50,
            step=1,
            group="Geometry",
            extended_help="**Floating Gaps**\n\nSpecific gap overrides applied only to windows currently in a floating state. Setting this to -1 inherits standard gap behavior."
        ),
        ConfigItem(
            label="Workspace Gaps",
            key="gaps_workspaces",
            scope="general",
            type_="int",
            default=50,
            min_val=0,
            max_val=50,
            step=1,
            group="Geometry",
            extended_help="**Workspace Gaps**\n\nAdds horizontal gap padding specifically between adjacent workspaces during transition animations."
        ),
    ],

    # -------------------------------------------------------------------------
    # TAB 2: COLORS
    # -------------------------------------------------------------------------
    2: [
        ConfigItem(
            label="Active Border",
            key="col.active_border",
            scope="general",
            type_="color",
            default="primary",
            options=COLOR_ALIASES,
            group="Borders",
            extended_help="**Active Border**\n\nThe highlight color surrounding the window currently receiving keyboard input."
        ),
        ConfigItem(
            label="Inactive Border",
            key="col.inactive_border",
            scope="general",
            type_="color",
            default="inverse_on_surface",
            options=COLOR_ALIASES,
            group="Borders",
            extended_help="**Inactive Border**\n\nThe color applied to all background windows that do not have focus."
        ),
        ConfigItem(
            label="No-Group Active Border",
            key="col.nogroup_border_active",
            scope="general",
            type_="color",
            default="secondary",
            options=COLOR_ALIASES,
            group="Borders",
            extended_help="**No-Group Active Border**\n\nSpecialized active border color for windows that explicitly deny being added to a tabbed group layout."
        ),
        ConfigItem(
            label="No-Group Inactive Border",
            key="col.nogroup_border",
            scope="general",
            type_="color",
            default="inverse_on_surface",
            options=COLOR_ALIASES,
            group="Borders",
            extended_help="**No-Group Inactive Border**\n\nSpecialized inactive border color for windows that explicitly deny being added to a tabbed group layout."
        ),
    ],

    # -------------------------------------------------------------------------
    # TAB 3: INTERACTIONS
    # -------------------------------------------------------------------------
    3: [
        ConfigItem(
            label="Resize on Border",
            key="resize_on_border",
            scope="general",
            type_="bool",
            default=True,
            group="Mouse",
            extended_help="**Resize on Border**\n\nAllows you to dynamically resize windows by clicking and dragging directly on their borders or gap areas."
        ),
        ConfigItem(
            label="Extend Border Grab Area",
            key="extend_border_grab_area",
            scope="general",
            type_="int",
            default=15,
            min_val=0,
            max_val=50,
            step=1,
            group="Mouse",
            extended_help="**Extend Grab Area**\n\nExtends the invisible clickable area around window borders. Higher values make it easier to grab."
        ),
        ConfigItem(
            label="Hover Icon on Border",
            key="hover_icon_on_border",
            scope="general",
            type_="bool",
            default=True,
            group="Mouse",
            extended_help="**Hover Icon**\n\nAutomatically changes your cursor to a directional resize arrow when hovering over an interactive border area."
        ),
        ConfigItem(
            label="Resize Corner",
            key="resize_corner",
            scope="general",
            type_="int",
            default=0,
            min_val=0,
            max_val=4,
            step=1,
            group="Behavior",
            extended_help="**Resize Corner**\n\nForces floating windows to strictly scale from a specific corner (1-4). Set to 0 to disable."
        ),
        ConfigItem(
            label="Allow Tearing",
            key="allow_tearing",
            scope="general",
            type_="bool",
            default=True,
            group="Behavior",
            extended_help="**Allow Tearing**\n\nMaster switch to allow screen tearing for immediate frame delivery, beneficial for minimizing input latency."
        ),
    ],

    # -------------------------------------------------------------------------
    # TAB 4: STYLING
    # -------------------------------------------------------------------------
    4: [
        ConfigItem(
            label="Rounding",
            key="rounding",
            scope="decoration",
            type_="int",
            default=6,
            min_val=0,
            max_val=50,
            step=1,
            group="Corners",
            extended_help="**Rounding**\n\nThe layout pixel radius for window corners. Set to 0 for sharp corners."
        ),
        ConfigItem(
            label="Rounding Power",
            key="rounding_power",
            scope="decoration",
            type_="float",
            default=2.0,
            min_val=1.0,
            max_val=4.0,
            step=0.1,
            group="Corners",
            extended_help="**Rounding Power**\n\nAdjusts the mathematical curve used to clip corners. 2.0 is circular, 4.0 is squircle, 1.0 is triangular."
        ),
        ConfigItem(
            label="Border Part of Window",
            key="border_part_of_window",
            scope="decoration",
            type_="bool",
            default=True,
            group="Corners",
            extended_help="**Border Part of Window**\n\nToggles whether the window border is drawn inside the application's allocated space or strictly on the outside."
        ),
        ConfigItem(
            label="Active Opacity",
            key="active_opacity",
            scope="decoration",
            type_="float",
            default=0.85,
            min_val=0.0,
            max_val=1.0,
            step=0.05,
            group="Opacity",
            extended_help="**Active Opacity**\n\nThe global transparency level for the window you are actively using."
        ),
        ConfigItem(
            label="Inactive Opacity",
            key="inactive_opacity",
            scope="decoration",
            type_="float",
            default=0.85,
            min_val=0.0,
            max_val=1.0,
            step=0.05,
            group="Opacity",
            extended_help="**Inactive Opacity**\n\nThe transparency level for background windows."
        ),
        ConfigItem(
            label="Fullscreen Opacity",
            key="fullscreen_opacity",
            scope="decoration",
            type_="float",
            default=1.0,
            min_val=0.0,
            max_val=1.0,
            step=0.05,
            group="Opacity",
            extended_help="**Fullscreen Opacity**\n\nForces a specific transparency level whenever a window enters a fullscreen state."
        ),
        ConfigItem(
            label="Screen Shader",
            key="screen_shader",
            scope="decoration",
            type_="string",
            default="",
            group="Pipeline",
            extended_help="**Screen Shader**\n\nPath to a custom fragment shader file applied at the very end of the rendering pipeline."
        ),
        ConfigItem(
            label="XWayland Force Zero Scaling",
            key="force_zero_scaling",
            scope="xwayland",
            type_="bool",
            default=True,
            group="Pipeline",
            extended_help="**XWayland Scaling**\n\nForces zero scaling for XWayland applications. This global tweak prevents older X11 apps from becoming blurry on fractional scaled Wayland monitors."
        ),

        ConfigItem(
            label="Dim Inactive",
            key="dim_inactive",
            scope="decoration",
            type_="bool",
            default=True,
            group="Dimming",
            extended_help="**Dim Inactive**\n\nAutomatically applies a dark overlay to all windows that do not currently possess keyboard focus."
        ),
        ConfigItem(
            label="Dim Strength",
            key="dim_strength",
            scope="decoration",
            type_="float",
            default=0.3,
            min_val=0.0,
            max_val=1.0,
            step=0.1,
            group="Dimming",
            extended_help="**Dim Strength**\n\nDictates the intensity of the darkness applied to inactive windows."
        ),
        ConfigItem(
            label="Dim Around",
            key="dim_around",
            scope="decoration",
            type_="float",
            default=0.4,
            min_val=0.0,
            max_val=1.0,
            step=0.1,
            group="Dimming",
            extended_help="**Dim Around**\n\nControls the dimming intensity triggered by specific window rules."
        ),
        ConfigItem(
            label="Dim Modal",
            key="dim_modal",
            scope="decoration",
            type_="bool",
            default=True,
            group="Dimming",
            extended_help="**Dim Modal**\n\nWhen a modal appears, this darkens the main application window beneath it."
        ),
    ],

    # -------------------------------------------------------------------------
    # TAB 5: EFFECTS
    # -------------------------------------------------------------------------
    5: [
        # --- BLUR HYBRID FOLDER ---
        ConfigItem(
            label="Blur Settings",
            key="enabled",
            scope="decoration/blur",
            type_="bool",
            default=True,
            is_parent=True,
            expanded=False,
            group="Blur",
            extended_help="**Blur Enabled**\n\nToggles the kawase blur engine for transparent interface elements."
        ),
        ConfigItem(
            label="Size",
            key="size",
            scope="decoration/blur",
            type_="int",
            default=6,
            min_val=1,
            max_val=30,
            step=1,
            parent_ref="decoration/blur.enabled",
            extended_help="**Blur Size**\n\nThe distance of the blur effect."
        ),
        ConfigItem(
            label="Passes",
            key="passes",
            scope="decoration/blur",
            type_="int",
            default=3,
            min_val=1,
            max_val=10,
            step=1,
            parent_ref="decoration/blur.enabled",
            extended_help="**Blur Passes**\n\nHow many times the blur algorithm is applied."
        ),
        ConfigItem(
            label="Ignore Opacity",
            key="ignore_opacity",
            scope="decoration/blur",
            type_="bool",
            default=True,
            parent_ref="decoration/blur.enabled",
            extended_help="**Ignore Opacity**\n\nForces the blur engine to render at full strength beneath transparent windows."
        ),
        ConfigItem(
            label="New Optimizations",
            key="new_optimizations",
            scope="decoration/blur",
            type_="bool",
            default=True,
            parent_ref="decoration/blur.enabled",
            extended_help="**New Optimizations**\n\nEnables aggressive bounding box math to reduce GPU load."
        ),
        ConfigItem(
            label="Xray",
            key="xray",
            scope="decoration/blur",
            type_="bool",
            default=False,
            parent_ref="decoration/blur.enabled",
            extended_help="**Xray**\n\nForces floating windows to ignore tiled windows behind them when calculating blur."
        ),
        ConfigItem(
            label="Noise",
            key="noise",
            scope="decoration/blur",
            type_="float",
            default=0.0117,
            min_val=0.0,
            max_val=1.0,
            step=0.01,
            parent_ref="decoration/blur.enabled",
            extended_help="**Noise**\n\nInjects static noise into blurred areas."
        ),
        ConfigItem(
            label="Contrast",
            key="contrast",
            scope="decoration/blur",
            type_="float",
            default=0.8916,
            min_val=0.0,
            max_val=2.0,
            step=0.1,
            parent_ref="decoration/blur.enabled",
            extended_help="**Contrast**\n\nAdjusts contrast scaling strictly within blurred regions."
        ),
        ConfigItem(
            label="Brightness",
            key="brightness",
            scope="decoration/blur",
            type_="float",
            default=0.8172,
            min_val=0.0,
            max_val=2.0,
            step=0.1,
            parent_ref="decoration/blur.enabled",
            extended_help="**Brightness**\n\nAdjusts base brightness scaling of blurred regions."
        ),
        ConfigItem(
            label="Vibrancy",
            key="vibrancy",
            scope="decoration/blur",
            type_="float",
            default=0.1696,
            min_val=0.0,
            max_val=1.0,
            step=0.05,
            parent_ref="decoration/blur.enabled",
            extended_help="**Vibrancy**\n\nBoosts saturation of colors caught in the blur."
        ),
        ConfigItem(
            label="Vibrancy Darkness",
            key="vibrancy_darkness",
            scope="decoration/blur",
            type_="float",
            default=0.0,
            min_val=0.0,
            max_val=1.0,
            step=0.05,
            parent_ref="decoration/blur.enabled",
            extended_help="**Vibrancy Darkness**\n\nDictates vibrancy saturation specifically for dark areas."
        ),
        ConfigItem(
            label="Popups",
            key="popups",
            scope="decoration/blur",
            type_="bool",
            default=False,
            parent_ref="decoration/blur.enabled",
            extended_help="**Popups**\n\nForces background blur behind context menus and tooltips."
        ),
        ConfigItem(
            label="Popups Ignore Alpha",
            key="popups_ignorealpha",
            scope="decoration/blur",
            type_="float",
            default=0.2,
            min_val=0.0,
            max_val=1.0,
            step=0.1,
            parent_ref="decoration/blur.enabled",
            extended_help="**Popups Ignore Alpha**\n\nIf popup pixel opacity is lower than this value, the blur engine ignores it."
        ),
        ConfigItem(
            label="Input Methods",
            key="input_methods",
            scope="decoration/blur",
            type_="bool",
            default=False,
            parent_ref="decoration/blur.enabled",
            extended_help="**Input Methods**\n\nForces background blur behind input method editor windows."
        ),
        ConfigItem(
            label="Input Methods Ignore Alpha",
            key="input_methods_ignorealpha",
            scope="decoration/blur",
            type_="float",
            default=0.2,
            min_val=0.0,
            max_val=1.0,
            step=0.1,
            parent_ref="decoration/blur.enabled",
            extended_help="**Input Methods Ignore Alpha**\n\nIf input method pixel opacity is lower than this value, the blur engine ignores it."
        ),

        # --- SHADOW HYBRID FOLDER ---
        ConfigItem(
            label="Shadow Settings",
            key="enabled",
            scope="decoration/shadow",
            type_="bool",
            default=True,
            is_parent=True,
            expanded=False,
            group="Shadows",
            extended_help="**Shadow Enabled**\n\nToggles drop shadows beneath active and floating windows."
        ),
        ConfigItem(
            label="Range",
            key="range",
            scope="decoration/shadow",
            type_="int",
            default=6,
            min_val=1,
            max_val=50,
            step=1,
            parent_ref="decoration/shadow.enabled",
            extended_help="**Range**\n\nThe physical distance in pixels that the shadow extends outward."
        ),
        ConfigItem(
            label="Render Power",
            key="render_power",
            scope="decoration/shadow",
            type_="int",
            default=1,
            min_val=1,
            max_val=4,
            step=1,
            parent_ref="decoration/shadow.enabled",
            extended_help="**Render Power**\n\nControls the decay rate of the shadow."
        ),
        ConfigItem(
            label="Sharp",
            key="sharp",
            scope="decoration/shadow",
            type_="bool",
            default=False,
            parent_ref="decoration/shadow.enabled",
            extended_help="**Sharp**\n\nRemoves standard diffusion, converting the shadow into a harsh, solid block color."
        ),
        ConfigItem(
            label="Color",
            key="color",
            scope="decoration/shadow",
            type_="color",
            default="rgba(1a1a1aee)",
            options=COLOR_ALIASES,
            parent_ref="decoration/shadow.enabled",
            extended_help="**Color**\n\nThe color of the drop shadow."
        ),
        ConfigItem(
            label="Scale",
            key="scale",
            scope="decoration/shadow",
            type_="float",
            default=1.0,
            min_val=0.0,
            max_val=1.0,
            step=0.1,
            parent_ref="decoration/shadow.enabled",
            extended_help="**Scale**\n\nMultiplies the physical size footprint of the shadow geometry."
        ),

        # --- GLOW HYBRID FOLDER ---
        ConfigItem(
            label="Glow Settings",
            key="enabled",
            scope="decoration/glow",
            type_="bool",
            default=False,
            is_parent=True,
            expanded=False,
            group="Glow",
            extended_help="**Glow Enabled**\n\nToggles inner window glow."
        ),
        ConfigItem(
            label="Range",
            key="range",
            scope="decoration/glow",
            type_="int",
            default=10,
            min_val=1,
            max_val=50,
            step=1,
            parent_ref="decoration/glow.enabled",
            extended_help="**Range**\n\nThe physical distance in pixels that the glow lighting bleeds outward."
        ),
        ConfigItem(
            label="Render Power",
            key="render_power",
            scope="decoration/glow",
            type_="int",
            default=3,
            min_val=1,
            max_val=4,
            step=1,
            parent_ref="decoration/glow.enabled",
            extended_help="**Render Power**\n\nControls the decay rate of the glow."
        ),
        ConfigItem(
            label="Color",
            key="color",
            scope="decoration/glow",
            type_="color",
            default="primary_container",
            options=COLOR_ALIASES,
            parent_ref="decoration/glow.enabled",
            extended_help="**Color**\n\nThe distinct color of the glow emission."
        ),
    ],

    # -------------------------------------------------------------------------
    # TAB 6: SMART (Contextual Overrides)
    # -------------------------------------------------------------------------
    6: [
        # --- SINGLE WINDOW EXCLUSIONS ---
        ConfigItem(
            label="Single Border Size",
            key="border_size",
            scope="workspace_rule/w[tv1]s[false]",
            type_="int",
            default=2,
            min_val=0,
            max_val=15,
            step=1,
            group="Single",
            extended_help="**Single Border Size**\n\nOverrides the border size specifically when there is exactly one tiled window on the workspace."
        ),
        ConfigItem(
            label="Single Gaps In",
            key="gaps_in",
            scope="workspace_rule/w[tv1]s[false]",
            type_="int",
            default=4,
            min_val=0,
            max_val=50,
            step=1,
            group="Single",
            extended_help="**Single Gaps In**\n\nOverrides the inner gaps when there is exactly one tiled window present."
        ),
        ConfigItem(
            label="Single Gaps Out",
            key="gaps_out",
            scope="workspace_rule/w[tv1]s[false]",
            type_="int",
            default=6,
            min_val=0,
            max_val=50,
            step=1,
            group="Single",
            extended_help="**Single Gaps Out**\n\nOverrides the outer gaps when there is exactly one tiled window present. Set to 0 to make single windows flush with the monitor edge."
        ),
        ConfigItem(
            label="Single Rounding",
            key="rounding",
            scope="window_rule/single_window_style",
            type_="int",
            default=6,
            min_val=0,
            max_val=50,
            step=1,
            group="Single",
            extended_help="**Single Rounding**\n\nOverrides the corner rounding radius when exactly one tiled window is present. Set to 0 to disable rounding for single windows."
        ),
        ConfigItem(
            label="Single Rounding Power",
            key="rounding_power",
            scope="window_rule/single_window_style",
            type_="float",
            default=2.0,
            min_val=1.0,
            max_val=4.0,
            step=0.1,
            group="Single",
            extended_help="**Single Rounding Power**\n\nOverrides the mathematical curve used for rounding corners specifically for single windows. 2.0 is circular, 4.0 is squircle, 1.0 is triangular."
        ),
        ConfigItem(
            label="Single Opacity Override",
            key="opacity",
            scope="window_rule/single_window_style",
            type_="float",
            default=1.0,
            min_val=0.0,
            max_val=1.0,
            step=0.05,
            group="Single",
            extended_help="**Single Opacity Override**\n\nAbsolute opacity rules applied to a single window."
        ),
        ConfigItem(
            label="Single Disable Blur",
            key="no_blur",
            scope="window_rule/single_window_style",
            type_="bool",
            default=False,
            group="Single",
            extended_help="**Single Disable Blur**\n\nDisables the background blur effect for the window when it is the only one on the screen to save GPU resources."
        ),

        # --- MAXIMIZED EXCLUSIONS ---
        ConfigItem(
            label="Maximized Border Size",
            key="border_size",
            scope="workspace_rule/f[1]s[false]",
            type_="int",
            default=1,
            min_val=0,
            max_val=15,
            step=1,
            group="Maximized",
            extended_help="**Maximized Border Size**\n\nOverrides the border size specifically when a maximized window is present on the workspace."
        ),
        ConfigItem(
            label="Maximized Gaps In",
            key="gaps_in",
            scope="workspace_rule/f[1]s[false]",
            type_="int",
            default=4,
            min_val=0,
            max_val=50,
            step=1,
            group="Maximized",
            extended_help="**Maximized Gaps In**\n\nOverrides the inner gaps specifically when a maximized window is present."
        ),
        ConfigItem(
            label="Maximized Gaps Out",
            key="gaps_out",
            scope="workspace_rule/f[1]s[false]",
            type_="int",
            default=8,
            min_val=0,
            max_val=50,
            step=1,
            group="Maximized",
            extended_help="**Maximized Gaps Out**\n\nOverrides the outer gaps specifically when a maximized window is present."
        ),
        ConfigItem(
            label="Maximized Rounding",
            key="rounding",
            scope="window_rule/maximized_window_style",
            type_="int",
            default=10,
            min_val=0,
            max_val=50,
            step=1,
            group="Maximized",
            extended_help="**Maximized Rounding**\n\nOverrides the corner rounding radius specifically for maximized windows."
        ),
        ConfigItem(
            label="Maximized Opacity",
            key="opacity",
            scope="window_rule/maximized_window_style",
            type_="float",
            default=1.0,
            min_val=0.0,
            max_val=1.0,
            step=0.05,
            group="Maximized",
            extended_help="**Maximized Opacity**\n\nForces a specific transparency level whenever a window enters a floating maximized state."
        ),
        ConfigItem(
            label="Maximized Disable Blur",
            key="no_blur",
            scope="window_rule/maximized_window_style",
            type_="bool",
            default=True,
            group="Maximized",
            extended_help="**Maximized Disable Blur**\n\nDisables the background blur effect entirely for maximized windows to maximize performance."
        ),
    ],

    # -------------------------------------------------------------------------
    # TAB 7: SPECIAL WORKSPACE
    # -------------------------------------------------------------------------
    7: [
        # --- BACKGROUND ---
        ConfigItem(
            label="Dim Background",
            key="dim_special",
            scope="decoration",
            type_="float",
            default=0.7,
            min_val=0.0,
            max_val=1.0,
            step=0.1,
            group="Background",
            extended_help="**Dim Special**\n\nControls how dark the rest of your screen becomes when a special workspace is open."
        ),
        ConfigItem(
            label="Blur Background",
            key="special",
            scope="decoration/blur",
            type_="bool",
            default=False,
            group="Background",
            extended_help="**Special Workspace Blur**\n\nForces kawase blur behind the entire screen when a special scratchpad workspace is open."
        ),

        # --- GEOMETRY ---
        ConfigItem(
            label="Border Size",
            key="border_size",
            scope="workspace_rule/special:magic",
            type_="int",
            default=3,
            min_val=0,
            max_val=30,
            step=1,
            group="Geometry",
            extended_help="**Magic Border Size**\n\nSets the absolute pixel width of the borders drawn around the magic scratchpad windows."
        ),
        ConfigItem(
            label="Gaps In",
            key="gaps_in",
            scope="workspace_rule/special:magic",
            type_="int",
            default=4,
            min_val=0,
            max_val=100,
            step=1,
            group="Geometry",
            extended_help="**Magic Gaps In**\n\nDefines the spacing between windows inside the magic scratchpad."
        ),
        ConfigItem(
            label="Gaps Out",
            key="gaps_out",
            scope="workspace_rule/special:magic",
            type_="int",
            default=20,
            min_val=0,
            max_val=200,
            step=1,
            group="Geometry",
            extended_help="**Magic Gaps Out**\n\nDefines the large outer margin around the magic scratchpad, making it feel centered and floating."
        ),

        # --- STYLING ---
        ConfigItem(
            label="Border Color",
            key="border_color",
            scope="window_rule/special_magic_style",
            type_="color",
            default="outline",
            options=COLOR_ALIASES,
            group="Styling",
            extended_help="**Magic Border Color**\n\nThe color of the border for windows in the magic scratchpad. Usually distinct from normal windows."
        ),
        ConfigItem(
            label="Rounding",
            key="rounding",
            scope="window_rule/special_magic_style",
            type_="int",
            default=6,
            min_val=0,
            max_val=50,
            step=1,
            group="Styling",
            extended_help="**Magic Rounding**\n\nThe corner rounding radius for magic scratchpad windows."
        ),
        ConfigItem(
            label="Rounding Power",
            key="rounding_power",
            scope="window_rule/special_magic_style",
            type_="float",
            default=2.0,
            min_val=1.0,
            max_val=4.0,
            step=0.1,
            group="Styling",
            extended_help="**Magic Rounding Power**\n\nAdjusts the mathematical curve used to clip corners. 2.0 is circular, 4.0 is squircle, 1.0 is triangular."
        ),
        ConfigItem(
            label="Opacity",
            key="opacity",
            scope="window_rule/special_magic_style",
            type_="float",
            default=0.92,
            min_val=0.0,
            max_val=1.0,
            step=0.05,
            group="Styling",
            extended_help="**Magic Opacity**\n\nThe transparency level for magic scratchpad windows."
        ),
        ConfigItem(
            label="Disable Blur",
            key="no_blur",
            scope="window_rule/special_magic_style",
            type_="bool",
            default=True,
            group="Styling",
            extended_help="**Magic Disable Blur**\n\nDisables the kawase background blur effect strictly for magic scratchpad windows."
        ),
    ]
}
