#!/usr/bin/env bash
#
# Arch Linux mkinitcpio Configuration Optimizer
# Context: Configures mkinitcpio drop-in for BTRFS/LUKS. Does NOT generate initramfs.
# Target: /etc/mkinitcpio.conf.d/10-arch-btrfs-luks.conf
#

# --- 1. Safety & Environment ---
set -euo pipefail
IFS=$'\n\t'

# Fail-fast: Ensure root execution
if (( EUID != 0 )); then
    printf "\e[31m[ERROR]\e[0m This script must be run as root.\n" >&2
    exit 1
fi

# --- 2. Visuals & Helpers ---
readonly BOLD=$'\e[1m'
readonly RESET=$'\e[0m'
readonly GREEN=$'\e[32m'
readonly BLUE=$'\e[34m'
readonly RED=$'\e[31m'
readonly YELLOW=$'\e[33m'

log_info() { printf "${BLUE}[INFO]${RESET} %s\n" "$1"; }
log_success() { printf "${GREEN}[SUCCESS]${RESET} %s\n" "$1"; }
log_error() { printf "${RED}[ERROR]${RESET} %s\n" "$1"; }
log_step() { printf "\n${BOLD}${YELLOW}>>> STEP: %s${RESET}\n" "$1"; }

ask_next_step() {
    local step_description="$1"
    printf "\n${BLUE}----------------------------------------------------------------${RESET}\n"
    printf "${BOLD}UPCOMING STEP:${RESET} %s\n" "$step_description"

    if [[ "${INTERACTIVE_MODE:-false}" == "false" ]]; then
        printf "${GREEN}>> Auto-proceeding...${RESET}\n"
        return 0
    fi

    while true; do
        read -r -p "Action: [P]roceed, [S]kip, or [Q]uit? (p/s/q) [Default: p]: " choice
        choice=${choice:-p}
        case "${choice,,}" in
            p|proceed|y|yes) return 0 ;;
            s|skip) log_info "Skipping step: $step_description"; return 1 ;;
            q|quit) log_info "User requested exit."; exit 0 ;;
            *) printf "Invalid choice.\n" ;;
        esac
    done
}

# --- 3. Dependency Validation ---
verify_dependencies() {
    local missing_deps=0

    # Using type -P for strict path resolution in Bash
    if ! type -P btrfs >/dev/null 2>&1; then
        log_error "btrfs-progs is not installed. Cannot configure mkinitcpio for BTRFS."
        missing_deps=1
    fi

    if ! type -P cryptsetup >/dev/null 2>&1; then
        log_error "cryptsetup is not installed. The sd-encrypt hook will fail to build."
        missing_deps=1
    fi

    if (( missing_deps > 0 )); then
        log_error "Dependency pre-flight checks failed. Aborting."
        exit 1
    fi
}

# --- 4. Main Logic ---

# Check/Set Interactive Mode
INTERACTIVE_MODE="${INTERACTIVE_MODE:-false}"

log_step "mkinitcpio.conf Optimization (Modern Drop-in Method)"

if ask_next_step "Configure mkinitcpio (BTRFS modules & Systemd LUKS hooks)"; then
    
    log_info "Running dependency pre-flight checks..."
    verify_dependencies
    log_success "Dependencies verified."

    readonly CONF_DIR="/etc/mkinitcpio.conf.d"
    readonly CONF_FILE="${CONF_DIR}/10-arch-btrfs-luks.conf"

    log_info "Deploying drop-in configuration to $CONF_FILE..."
    
    # Securely create directory with explicit 0755 permissions
    install -d -m0755 "$CONF_DIR"
    
    # Write the optimized configuration
    cat << 'EOF' > "$CONF_FILE"
# BTRFS and LUKS configuration
# Generated by Arch Orchestrator
MODULES=(btrfs i915 amdgpu nouveau virtio-gpu qxl vmwgfx)
BINARIES=(/usr/bin/btrfs)
HOOKS=(systemd keyboard autodetect microcode modconf kms sd-vconsole block sd-encrypt filesystems)
EOF
    
    # Enforce strict permissions on the config file
    chmod 0644 "$CONF_FILE"
            
    log_success "mkinitcpio drop-in deployed successfully."
    log_info "NOTE: Initramfs generation will occur in a later step."
fi
