window=region
region=
fps=60
cursor=yes
encoder=gpu
codec=auto
quality=very_high
bitrate_mode=auto
frame_mode=content
color_range=limited
tune=performance
low_power=no
container=mp4
output_dir=~/Videos
audio_codec=opus
audio_bitrate=128
replay_buffer=0
replay_storage=ram
restart_replay=no
date_folders=no
show_indicator=yes
audio_output=default_output
audio_input=none
