-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#0a1612',
  base01 = '#05100d',
  base02 = '#121e1a',
  base03 = '#3d4945',
  base04 = '#bccac3',
  base05 = '#d8e6df',
  base06 = '#27332f',
  base07 = '#2f3c37',

  base08 = '#ffb4ab',
  base09 = '#8dd2da',
  base0A = '#a0d0cb',
  base0B = '#00e0b8',
  base0C = '#004f55',
  base0D = '#005141',
  base0E = '#1f4e4b',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#005141',
  fg = '#0a1612',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#a8eef7',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#8dd2da',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#a0d0cb',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#006b57',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#05100d',
  fg = '#00e0b8',
})
