-- DO NOT EDIT THIS FILE, if you want to configure something, edit the file
-- at this location. ~/.config/hypr/edit_here/source/

-- You can also use the TUI `Hypr Keybind Manager` from the rofi menu to change keybinds. It automatically
-- unbinds keybinds and checks for conflicts. 

-- -------------------------------------------------------------------------------------------------
-- window classes to not have global keybinds applied in
-- -------------------------------------------------------------------------------------------------

local function is_target_app_active()
    local w = hl.get_active_window()
    if not w then return false end
    local class = w.class or ""
    return class == "horizon_tui" or class == "wallpaper_selector.py" or class == "terminal_clipboard.sh"
end

local function cond_bind(key, default_dsp, flags)
    hl.bind(key, function()
        if is_target_app_active() then
            hl.dispatch(hl.dsp.pass({ window = "activewindow" }))
        else
            if default_dsp then
                hl.dispatch(default_dsp)
            else
                hl.dispatch(hl.dsp.pass({ window = "activewindow" }))
            end
        end
    end, flags)
end


-- -------------------------------------------------------------------------------------------------
-- HYPRLAND KEYBINDINGS
-- -------------------------------------------------------------------------------------------------
--
-- terminal    = "foot"
-- fileManager = "thunar"
-- menu        = "rofi -show drun"
-- browser     = "firefox"
-- textEditor  = "mousepad"
--
-- -- Path shortcut for cleaner config
--
--
-- -- -------------------------------------------------------------------------------------------------
-- -- 2. APPLICATION LAUNCHERS
-- -- -------------------------------------------------------------------------------------------------
--
-- hl.bind(
--     "SUPER + Q",
--     hl.dsp.exec_cmd(terminal),
--     { description = "Launch Terminal" }
-- )
-- 
-- hl.bind(
--     "SUPER + W",
--     hl.dsp.exec_cmd(browser),
--     { description = "Launch Browser" }
-- )
-- 
-- hl.bind(
--     "SUPER + E",
--     hl.dsp.exec_cmd(fileManager),
--     { description = "File Manager" }
-- )
-- 
-- hl.bind(
--     "SUPER + R",
--     hl.dsp.exec_cmd(textEditor),
--     { description = "Open Text Editor" }
-- )

hl.bind(
    "ALT + SPACE",
    hl.dsp.exec_cmd([[pkill rofi; rofi -show drun -run-command "{cmd}"]]),
    { description = "Launch Menu for Apps" }
)

hl.bind(
    "CTRL + SHIFT + code:61",
    hl.dsp.exec_cmd("pkill rofi; " .. horizon_scripts .. "rofi/keybindings.sh"),
    { description = "Show Keybinds" }
)

hl.bind(
    "SUPER + CTRL + SPACE",
    hl.dsp.exec_cmd("pkill rofi; " .. horizon_scripts .. "rofi/emoji.sh"),
    { description = "Search Emojis" }
)

hl.bind(
    "SUPER + CTRL + SHIFT + SPACE",
    hl.dsp.exec_cmd("pkill rofi; " .. horizon_scripts .. "rofi/calculator.sh"),
    { description = "Calculator" }
)

hl.bind(
    "SUPER + SHIFT + SPACE",
    hl.dsp.exec_cmd("pkill rofi; " .. horizon_scripts .. "rofi/rofi_theme.sh"),
    { description = "Matugen Theme Config" }
)

hl.bind(
    "CTRL + SPACE",
    hl.dsp.exec_cmd([[pkill rofi; rofi -show drun]]),
    { description = "App Launcher" }
)

hl.bind(
    "SUPER + SPACE",
    hl.dsp.exec_cmd([[gdbus call --session --dest com.github.horizon.controlcenter --object-path /com/github/horizon/controlcenter --method org.freedesktop.Application.Activate "{}"]]),
    { description = "System Menu" }
)

hl.bind(
    "CTRL + ALT + SPACE",
    hl.dsp.exec_cmd("pkill rofi; " .. horizon_scripts .. "rofi/horizon_glance.sh"),
    { description = "Horizon Glance" }
)

-- Rofi Powermenu
hl.bind(
    "ALT + SHIFT + SPACE",
    hl.dsp.exec_cmd("pkill rofi; rofi -show power-menu -modi power-menu:" .. horizon_scripts .. "rofi/powermenu.sh"),
    { description = "Power Menu" }
)

-- System Monitor (btop)
hl.bind(
    "CTRL + SHIFT + escape",
    hl.dsp.exec_cmd(terminal .. " --class btop -e btop"),
    { description = "System Monitor" }
)


-- -------------------------------------------------------------------------------------------------
-- 3. SYSTEM UTILITIES & TOGGLES
-- -------------------------------------------------------------------------------------------------

hl.bind(
    "ALT + 1",
    hl.dsp.exec_cmd("foot --app-id=horizon_tui python $HOME/user_scripts/horizon_tui/python/main/main.py $HOME/user_scripts/network_manager/tui_horizon_network.py"),
    { description = "Wi-Fi Manager" }
)

hl.bind(
    "ALT + 2",
    hl.dsp.exec_cmd("blueman-manager"),
    { description = "Bluetooth Manager" }
)

hl.bind(
    "ALT + 3",
    hl.dsp.exec_cmd("pavucontrol"),
    { description = "Audio Mixer" }
)

hl.bind(
    "ALT + 4",
    hl.dsp.exec_cmd(horizon_scripts .. "images/wallpaper_selector.py"),
    { description = "Horizon Wallpaper Selector" }
)

hl.bind(
    "SUPER + apostrophe",
    hl.dsp.exec_cmd(horizon_scripts .. "theme_matugen/theme_ctl.sh next"),
    { description = "Cycle Next Wallpaper" }
)

hl.bind(
    "SUPER + SHIFT + apostrophe",
    hl.dsp.exec_cmd(horizon_scripts .. "images/wallpaper_selector.py --next-fav"),
    { description = "Cycle Fav Wallpaper" }
)

hl.bind(
    "ALT + 5",
    hl.dsp.exec_cmd(terminal .. " -e " .. horizon_scripts .. "drives/drive_manager.sh unlock browser"),
    { description = "Unlock Browser" }
)

hl.bind(
    "ALT + SHIFT + 5",
    hl.dsp.exec_cmd(terminal .. " -e " .. horizon_scripts .. "drives/drive_manager.sh lock browser"),
    { description = "Lock Browser", locked = true }
)


-------------------------------------------------------------
--- DELETE AFTER HYPRLAND MERGES THE FIX
-- --- Passthrough (Disable keybinds) ---
--hl.bind(
--    "ALT + 6",
--    function()
--        hl.notification.create({ text = "Passthrough Enabled - Press 'ALT SHIFT 6' to exit", timeout = 6000 })
--        hl.dispatch(hl.dsp.submap("passthrough"))
--    end,
--    { description = "Enable Game Mode (Disable Keybinds)", locked = true }
--)
--
--hl.define_submap("passthrough", function()
--    hl.bind(
--        "ALT + SHIFT + 6",
--        function()
--            hl.notification.create({ text = "Passthrough Disabled - Keybinds restored", timeout = 2000 })
--            hl.dispatch(hl.dsp.submap("reset"))
--        end,
--        { description = "Disable Game Mode (Restore Keybinds)", locked = true }
--    )
--end)
-----------------------------------------------------------------
--- Uncomment after hyprland merges the fix
----------------------------------------------------------------
-- --- Passthrough (Disable keybinds) ---
-- ⚠ Requires Hyprland built after May 29 2026 (PR #14856)

 local SUBMAP_MANUAL_PT = "keybinds_disabled"  -- NOT "passthrough" (reserved dispatcher name)

 hl.bind(
     "ALT + 6",
     function()
         hl.notification.create({ text = "Passthrough Enabled - Press ALT+6 to exit", timeout = 3000 })
         hl.dispatch(hl.dsp.submap(SUBMAP_MANUAL_PT))
     end,
     { description = "Enable Game Mode (Disable Keybinds)", locked = true }
 )

 hl.define_submap(SUBMAP_MANUAL_PT, function()
     hl.bind(
         "ALT + 6",   -- ← same key now works with the #14856 fix
         function()
             hl.notification.create({ text = "Passthrough Disabled - Keybinds restored", timeout = 2000 })
             hl.dispatch(hl.dsp.submap("reset"))
         end,
         { description = "Disable Game Mode (Restore Keybinds)", locked = true }
     )
 end)


hl.bind(
    "CTRL + ALT + R",
    hl.dsp.exec_cmd(horizon_scripts .. "hypr/monitor/screen_rotate.py -90"),
    { description = "Rotate Screen Clockwise", locked = true, repeating = true }
)

hl.bind(
    "CTRL + ALT + SHIFT + R",
    hl.dsp.exec_cmd(horizon_scripts .. "hypr/monitor/screen_rotate.py +90"),
    { description = "Rotate Screen Anti-Clockwise", locked = true, repeating = true }
)

hl.bind(
    "ALT + F7",
    function()
        hl.timer(function()
            hl.dispatch(hl.dsp.dpms({ action = "disable" }))
        end, { timeout = 500, type = "oneshot" })
    end,
    { description = "Screen Off DPMS", locked = true }
)

hl.bind(
    "ALT + F8",
    function()
        hl.timer(function()
            hl.dispatch(hl.dsp.dpms({ action = "enable" }))
        end, { timeout = 500, type = "oneshot" })
    end,
    { description = "Screen On DPMS", locked = true }
)



-- --- Waybar Toggle ---
hl.bind(
    "ALT + 9",
    hl.dsp.exec_cmd(horizon_scripts .. "waybar/waybar_toggle.sh"),
    { description = "Start Waybar for 1 Min" }
)

hl.bind(
    "ALT + 0",
    hl.dsp.exec_cmd("pkill tray-tui; foot --app-id=horizon_tui tray-tui"),
    { description = "system Tray TUI" }
)

hl.bind(
    "SUPER + ALT + W",
    hl.dsp.exec_cmd(horizon_scripts .. "waybar/wrapper_waybar_swapper.py --next"),
    { description = "Waybar Swap Configs" }
)

hl.bind(
    "SUPER + ALT + SHIFT + W",
    hl.dsp.exec_cmd(horizon_scripts .. "waybar/wrapper_waybar_swapper.py --prev"),
    { description = "Waybar Swap Configs" }
)


-- --- Utilities ---
hl.bind(
    "ALT + F4",
    hl.dsp.exec_cmd(horizon_scripts .. "wlogout/wlogout_scale.sh"),
    { description = "Logout Menu" }
)

hl.bind(
    "SUPER + SHIFT + R",
    hl.dsp.exec_cmd("hyprctl reload"),
    { description = "Reload Hyprland", locked = true }
)

cond_bind(
    "ALT + V",
    hl.dsp.exec_cmd([[gdbus call --session --dest org.horizon.quickpanal --object-path /org/horizon/quickpanal --method org.freedesktop.Application.Activate "{}"]]),
    { description = "Horizon QuickPanal" }
)

hl.bind(
    "SUPER + F",
    hl.dsp.exec_cmd(horizon_scripts .. "hypr/monitor/adjust_scale.py +"),
    { description = "Scale Up", locked = true, repeating = true }
)

hl.bind(
    "SUPER + SHIFT + F",
    hl.dsp.exec_cmd(horizon_scripts .. "hypr/monitor/adjust_scale.py -"),
    { description = "Scale Down", locked = true, repeating = true }
)

hl.bind(
    "SUPER + semicolon",
    hl.dsp.exec_cmd(terminal .. " --class performance.sh -e " .. horizon_scripts .. "performance/services_and_process_terminator.sh"),
    { description = "Kill Process" }
)

-- --- Wayclick & OSD Key Presses ---
hl.bind(
    "SUPER + U",
    hl.dsp.exec_cmd(horizon_scripts .. "wayclick/horizon_wayclick.sh"),
    { description = "Key Press Sound" }
)

hl.bind(
    "SUPER + SHIFT + U",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/horizon_keys/horizon_keys.sh"),
    { description = "OSD KEY Presses" }
)

-- --- Hyprshade (Visual Filters) ---
hl.bind(
    "SUPER + ALT + S",
    hl.dsp.exec_cmd("pkill rofi; " .. horizon_scripts .. "rofi/shader_menu.sh"),
    { description = "Shader Menu" }
)


hl.bind(
    "SUPER + ALT + X",
    hl.dsp.exec_cmd("hyprshade off"),
    { description = "Disable Shader", locked = true }
)

hl.bind(
    "SUPER + ALT + V",
    hl.dsp.exec_cmd("hyprshade on vibrance"),
    { description = "Vibrant Shader", locked = true }
)

-- --- Hyprland Animations ---
hl.bind(
    "SUPER + ALT + A",
    hl.dsp.exec_cmd("pkill rofi; rofi -show animations -modi \"animations:" .. horizon_scripts .. "rofi/hypr_anim.sh\""),
    { description = "Hyprland Animation Rofi Menu" }
)

-- --- Special Workspace (Spotify) ---
hl.bind(
    "SUPER + SHIFT + M",
    hl.dsp.exec_cmd(horizon_scripts .. "spotify/spotify_toggle.sh"),
    { description = "Special Workspace for Spotify" }
)


-- --- Opacity & Blur Toggles ---
hl.bind(
    "SUPER + ALT + period",
    hl.dsp.exec_cmd(horizon_scripts .. "hypr/hypr_blur_opacity_shadow_toggle.sh"),
    { description = "Toggle Blur/Opacity", locked = true }
)

hl.bind(
    "SUPER + period",
    hl.dsp.window.set_prop({ prop = "opaque", value = "toggle", window = "activewindow" }),
    { description = "Toggle Opacity", locked = true }
)

hl.bind(
    "SUPER + comma",
    hl.dsp.window.set_prop({ prop = "no_blur", value = "toggle", window = "activewindow" }),
    { description = "Toggle Per-Window Blur", locked = true }
)


-- --- Accessibility: Zoom ---
hl.config({ cursor = { zoom_disable_aa = true } })

hl.bind(
    "SUPER + equal",
    function()
        local z = hl.get_config("cursor.zoom_factor")
        hl.config({ cursor = { zoom_factor = z * 1.25 } })
    end,
    { description = "Zoom In", repeating = true }
)

hl.bind(
    "SUPER + minus",
    function()
        local z = hl.get_config("cursor.zoom_factor")
        local nz = z / 1.25
        if nz < 1.0 then nz = 1.0 end
        hl.config({ cursor = { zoom_factor = nz } })
    end,
    { description = "Zoom Out", repeating = true }
)

hl.bind(
    "SUPER + BACKSPACE",
    function()
        hl.config({ cursor = { zoom_factor = 1.0 } })
    end,
    { description = "Reset Zoom", locked = true }
)


-- --- Clipboard & Screenshot ---
-- hl.bind(
--     "SUPER + V",
--     hl.dsp.exec_cmd("pkill rofi; rofi -modi \"clipboard:" .. horizon_scripts .. "rofi/rofi_cliphist.sh\" -show clipboard"),
--     { description = "Clipboard History" }
-- )

hl.bind("SUPER + V", function()
    -- Kill any existing clipboard foot instance with SIGTERM (-15).
    -- The '^foot' anchor is critical: it means only processes whose
    -- cmdline STARTS with 'foot' are matched. The sh subprocess spawned
    -- by os.execute starts with 'sh', so it can never self-match.
    -- This eliminates the self-terminating sh -c wrapper bug.
    os.execute("pkill -15 -f '^foot.*terminal_clipboard'")

    -- Dispatch the fresh instance. hl.dispatch + exec_cmd spawns
    -- foot directly without a sh -c wrapper, so there are no shell
    -- chain issues here. os.getenv() expands $HOME safely in Lua.
    hl.dispatch(hl.dsp.exec_cmd(
        "foot --app-id=terminal_clipboard.sh " ..
        os.getenv("HOME") .. "/user_scripts/clipboard/terminal_clipboard.sh"
    ))
end, { description = "Clipboard History" })


hl.bind(
    "SUPER + B",
    hl.dsp.exec_cmd("pkill hyprpicker || hyprpicker -a"),
    { description = "Color Picker" }
)

hl.bind(
    "SUPER + SHIFT + S",
    hl.dsp.exec_cmd(horizon_scripts .. "images/horizon_screenshot.sh --region --freeze --no-notify"),
    { description = "Quick Screenshot" }
)

hl.bind(
    "SHIFT + Print",
    hl.dsp.exec_cmd([[grim - | wl-copy && notify-send "Fullscreen Screenshot in Clipboard"]]),
    { description = "Full Screen Quick Screenshot", locked = true }
)

hl.bind(
    "SUPER + SHIFT + S",
    hl.dsp.exec_cmd(horizon_scripts .. "images/horizon_screenshot.sh --region --freeze --annotate --no-notify --tool arrow"),
    { description = "Screenshot and Annotation" }
)

hl.bind(
    "Print",
    hl.dsp.exec_cmd("pgrep -x swappy || (grim - | satty -f -)"),
    { description = "Fullscreen Screenshot and Annotation" }
)

hl.bind(
    "SHIFT + CTRL + ALT + space",
    hl.dsp.exec_cmd("pkill rofi; " .. horizon_scripts .. "rofi/horizon_rofi_screenshot.sh"),
    { description = "Horizon Screenshoter" }
)


-- --- Screen Recorder ---
cond_bind(
    "ALT + R",
    hl.dsp.exec_cmd("pkill rofi; " ..horizon_scripts .. "horizon_recorder/horizon_recorder.sh"),
    { description = "Screen Recorder" }
)


-- --- AI & Voice Tools ---

-- Google Image Search
hl.bind(
    "SUPER + G",
    hl.dsp.exec_cmd(horizon_scripts .. "google_image_search/google_image_search.sh"),
    { description = "Image Search (Select and search)" }
)

-- OCR (Tesseract)
hl.bind(
    "SUPER + T",
    hl.dsp.exec_cmd("pgrep tesseract || (slurp | grim -g - - | tesseract stdin stdout -l eng | wl-copy)"),
    { description = "OCR Selection" }
)

hl.bind(
    "SUPER + SHIFT + T",
    hl.dsp.exec_cmd("grim - | tesseract stdin stdout -l eng | wl-copy"),
    { description = "OCR Fullscreen" }
)

-- ollama Sidebar
hl.bind(
    "SUPER + ALT + O",
    hl.dsp.exec_cmd(terminal .. " --class ollama_terminal.sh -e " .. horizon_scripts .. "llm/ollama_terminal.sh"),
    { description = "AI LLM Ollama Chat" }
)

-- Music Recognition
hl.bind(
    "SUPER + ALT + M",
    hl.dsp.exec_cmd(terminal .. " --class music_recognition.sh --hold  " .. horizon_scripts .. "music/music_recognition.sh"),
    { description = "Music Recognition aka Shazam" }
)

-- Kokoro TTS
hl.bind(
    "SUPER + O",
    hl.dsp.exec_cmd("wl-copy \"$(wl-paste -p)\" && " .. horizon_scripts .. "tts_stt/horizon_kokoro/trigger.sh"),
    { description = "TTS Kokoro GPU" }
)

-- Kokoro TTS - VC Routed
hl.bind(
    "SUPER + SHIFT + O",
    hl.dsp.exec_cmd(horizon_scripts .. "audio/router/TTS_VC.sh"),
    { description = "TTS VC" }
)

-- NVIDIA Parakeet
hl.bind(
    "SUPER + I",
    hl.dsp.exec_cmd(horizon_scripts .. "tts_stt/horizon_parakeet/trigger.sh"),
    { description = "STT Parakeet GPU" }
)

-- FasterWhisper STT
-- hl.bind(
--     "SUPER + SHIFT + I",
--     hl.dsp.exec_cmd(horizon_scripts .. "tts_stt/faster_whisper/faster_whisper_stt.sh"),
--     { description = "STT Whisper CPU" }
-- )


-- ======================================
-- NOTIFICATION ACTIONS (MAKO + ROFI)
-- ======================================

-- --- Notification Panel ---
hl.bind(
    "SUPER + N",
    hl.dsp.exec_cmd("pkill rofi; " .. horizon_scripts .. "rofi/rofi_mako.sh"),
    { description = "Notification History" }
)

-- --- mako Clear all screen notifications ---
hl.bind(
    "SUPER + ALT + D",
    hl.dsp.exec_cmd("makoctl dismiss -a"),
    { description = "Clear Screen Notifications", locked = true }
)

hl.bind(
    "SUPER + ALT + F",
    hl.dsp.exec_cmd([[makoctl menu -- rofi -dmenu -p "Action: "]]),
    { description = "Interact with the current notification (answer Yes/No prompts)" }
)

-- --- Screen Lock ---
hl.bind(
    "SUPER + M",
    hl.dsp.exec_cmd(horizon_scripts .. "hyprlock/lock.sh"),
    { description = "Lock Screen" }
)


-- -------------------------------------------------------------------------------------------------
-- 4. WINDOW MANAGEMENT
-- -------------------------------------------------------------------------------------------------

hl.bind(
    "SUPER + C",
    hl.dsp.window.close(),
    { description = "Close Window" }
)

-- ----
-- Bind this at your own risk (In Beta)
-- ----
--
-- /user_scripts/tools/workspace/close-workspace.sh -- Working Feature but Unsure
-- hl.bind(
--    "CTRL + escape",
--    hl.dsp.exec_cmd(horizon_scripts .. "tools/workspace/close-workspace.sh"),
--    { description = "Close Workspace" }
-- )
-- ----
-- /user_scripts/tools/workspace/safety-close.sh -- Working Feature but Unsure
-- hl.bind(
--     "SUPER + SHIFT + B",
--     hl.dsp.exec_cmd(horizon_scripts .. "tools/workspace/safety-close.sh"),
--     { description = "Safety Close Window" }
-- )
-- ----

hl.bind(
    "SUPER + SHIFT + C",
    hl.dsp.exec_cmd(horizon_scripts .. "hypr/pkill/kill_focused_process.sh"),
    { description = "Kill Focused Process Completely"}
)



hl.bind(
    "SUPER + F11",
    hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }),
    { description = "Window Fullscreen" }
)

hl.bind(
    "SUPER + SHIFT + A",
    hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }),
    { description = "Window Maximize" }
)

hl.bind(
    "SUPER + X",
    hl.dsp.window.pin(),
    { description = "Pin Window" }
)

--------------------------------------------------------------------
-- Split requiers preserve_split to be true managed in another config
--------------------------------------------------------------------
-- hl.config({
--     dwindle = {
--         preserve_split = true,
--     },
-- })

hl.bind(
    "SUPER + Y",
    hl.dsp.layout("togglesplit"),
    { description = "Toggle Window Split" }
)
---------------------------------------------
hl.bind(
    "SUPER + F",
    hl.dsp.exec_cmd([[
        if hyprctl activewindow | grep -q 'floating: 0'; then
            W=$(hyprctl monitors -j | jq '.[] | select(.focused) | ((.width / .scale) * 0.9) | floor')
            H=$(hyprctl monitors -j | jq '.[] | select(.focused) | ((.height / .scale) * 0.9) | floor')
            hyprctl --batch "dispatch hl.dsp.window.float({action='set'}); dispatch hl.dsp.window.resize({x=${W}, y=${H}, relative=false})"
            hyprctl dispatch "hl.dsp.window.center()"
        else
            hyprctl dispatch "hl.dsp.window.float({action='unset'})"
        fi
    ]]),
    { description = "Smart Float" }
)


hl.bind(
    "SUPER + SHIFT + D",
    hl.dsp.window.pseudo({ action = "toggle" }),
    { description = "Toggle Pseudo" }
)


-- --- Focus Movement ---
hl.bind(
    "SUPER + a",
    hl.dsp.focus({ direction = "l" }),
    { description = "Focus Left", repeating = true }
)

hl.bind(
    "SUPER + d",
    hl.dsp.focus({ direction = "r" }),
    { description = "Focus Right", repeating = true }
)

hl.bind(
    "SUPER + w",
    hl.dsp.focus({ direction = "u" }),
    { description = "Focus Up", repeating = true }
)

hl.bind(
    "SUPER + s",
    hl.dsp.focus({ direction = "d" }),
    { description = "Focus Down", repeating = true }
)


-- --- Window Movement ---
hl.bind(
    "SUPER + CTRL + a",
    hl.dsp.window.move({ direction = "l" }),
    { description = "Move Left", repeating = true }
)

hl.bind(
    "SUPER + CTRL + d",
    hl.dsp.window.move({ direction = "r" }),
    { description = "Move Right", repeating = true }
)

hl.bind(
    "SUPER + CTRL + w",
    hl.dsp.window.move({ direction = "u" }),
    { description = "Move Up", repeating = true }
)

hl.bind(
    "SUPER + CTRL + s",
    hl.dsp.window.move({ direction = "d" }),
    { description = "Move Down", repeating = true }
)


-- --- Window Resizing ---
hl.bind(
    "SUPER + right",
    hl.dsp.window.resize({ x = 30, y = 0, relative = true }),
    { description = "Resize Width +", repeating = true }
)

hl.bind(
    "SUPER + left",
    hl.dsp.window.resize({ x = -30, y = 0, relative = true }),
    { description = "Resize Width -", repeating = true }
)

hl.bind(
    "SUPER + up",
    hl.dsp.window.resize({ x = 0, y = -30, relative = true }),
    { description = "Resize Height -", repeating = true }
)

hl.bind(
    "SUPER + down",
    hl.dsp.window.resize({ x = 0, y = 30, relative = true }),
    { description = "Resize Height +", repeating = true }
)


-- -------------------------------------------------------------------------------------------------
-- 5. WORKSPACE MANAGEMENT
-- -------------------------------------------------------------------------------------------------

hl.bind(
    "SUPER + TAB",
    hl.dsp.focus({ workspace = "previous" }),
    { description = "Last Workspace", repeating = true }
)

hl.bind(
    "ALT + SHIFT + TAB",
    hl.dsp.focus({ workspace = "e-1" }),
    { description = "Cycle Backward", repeating = true }
)

hl.bind(
    "SUPER + SHIFT + TAB",
    hl.dsp.focus({ workspace = "e+1" }),
    { description = "Cycle Next WS", repeating = true }
)

hl.bind(
    "SUPER + mouse_down",
    hl.dsp.focus({ workspace = "e+1" }),
    { description = "Cycle Next Workspace" }
)

hl.bind(
    "SUPER + mouse_up",
    hl.dsp.focus({ workspace = "e-1" }),
    { description = "Cycle Previous Workspace" }
)

hl.bind(
    "SUPER + Z",
    hl.dsp.workspace.toggle_special("magic"),
    { description = "Toggle Scratchpad" }
)

hl.bind(
    "SUPER + SHIFT + Z",
    hl.dsp.window.move({ workspace = "special:magic" }),
    { description = "Move to Scratchpad" }
)


------------------------------------------------------
-- SINGLE MONITOR
-----------------------------------------------------


-- -- Explicitly Unrolled Workspaces
-- 
-- -- Focus Workspace 
-- hl.bind(
--     "SUPER + 1",
--     hl.dsp.focus({ workspace = "1" }),
--     { description = "Switch To Workspace 1" }
-- )
-- hl.bind(
--     "SUPER + 2",
--     hl.dsp.focus({ workspace = "2" }),
--     { description = "Switch To Workspace 2" }
-- )
-- hl.bind(
--     "SUPER + 3",
--     hl.dsp.focus({ workspace = "3" }),
--     { description = "Switch To Workspace 3" }
-- )
-- hl.bind(
--     "SUPER + 4",
--     hl.dsp.focus({ workspace = "4" }),
--     { description = "Switch To Workspace 4" }
-- )
-- hl.bind(
--     "SUPER + 5",
--     hl.dsp.focus({ workspace = "5" }),
--     { description = "Switch To Workspace 5" }
-- )
-- hl.bind(
--     "SUPER + 6",
--     hl.dsp.focus({ workspace = "6" }),
--     { description = "Switch To Workspace 6" }
-- )
-- hl.bind(
--     "SUPER + 7",
--     hl.dsp.focus({ workspace = "7" }),
--     { description = "Switch To Workspace 7" }
-- )
-- hl.bind(
--     "SUPER + 8",
--     hl.dsp.focus({ workspace = "8" }),
--     { description = "Switch To Workspace 8" }
-- )
-- hl.bind(
--     "SUPER + 9",
--     hl.dsp.focus({ workspace = "9" }),
--     { description = "Switch To Workspace 9" }
-- )
-- hl.bind(
--     "SUPER + 0",
--     hl.dsp.focus({ workspace = "10" }),
--     { description = "Switch To Workspace 10" }
-- )
-- 
-- -- Move Window to Workspace
-- hl.bind(
--     "SUPER + SHIFT + 1",
--     hl.dsp.window.move({ workspace = "1" }),
--     { description = "Move To Workspace 1" }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 2",
--     hl.dsp.window.move({ workspace = "2" }),
--     { description = "Move To Workspace 2" }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 3",
--     hl.dsp.window.move({ workspace = "3" }),
--     { description = "Move To Workspace 3" }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 4",
--     hl.dsp.window.move({ workspace = "4" }),
--     { description = "Move To Workspace 4" }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 5",
--     hl.dsp.window.move({ workspace = "5" }),
--     { description = "Move To Workspace 5" }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 6",
--     hl.dsp.window.move({ workspace = "6" }),
--     { description = "Move To Workspace 6" }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 7",
--     hl.dsp.window.move({ workspace = "7" }),
--     { description = "Move To Workspace 7" }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 8",
--     hl.dsp.window.move({ workspace = "8" }),
--     { description = "Move To Workspace 8" }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 9",
--     hl.dsp.window.move({ workspace = "9" }),
--     { description = "Move To Workspace 9" }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 0",
--     hl.dsp.window.move({ workspace = "10" }),
--     { description = "Move To Workspace 10" }
-- )
-- 
-- -- Move Window Silently to Workspace
-- hl.bind(
--     "SUPER + ALT + 1",
--     hl.dsp.window.move({ workspace = "1", follow = false }),
--     { description = "Move Silently To Workspace 1" }
-- )
-- hl.bind(
--     "SUPER + ALT + 2",
--     hl.dsp.window.move({ workspace = "2", follow = false }),
--     { description = "Move Silently To Workspace 2" }
-- )
-- hl.bind(
--     "SUPER + ALT + 3",
--     hl.dsp.window.move({ workspace = "3", follow = false }),
--     { description = "Move Silently To Workspace 3" }
-- )
-- hl.bind(
--     "SUPER + ALT + 4",
--     hl.dsp.window.move({ workspace = "4", follow = false }),
--     { description = "Move Silently To Workspace 4" }
-- )
-- hl.bind(
--     "SUPER + ALT + 5",
--     hl.dsp.window.move({ workspace = "5", follow = false }),
--     { description = "Move Silently To Workspace 5" }
-- )
-- hl.bind(
--     "SUPER + ALT + 6",
--     hl.dsp.window.move({ workspace = "6", follow = false }),
--     { description = "Move Silently To Workspace 6" }
-- )
-- hl.bind(
--     "SUPER + ALT + 7",
--     hl.dsp.window.move({ workspace = "7", follow = false }),
--     { description = "Move Silently To Workspace 7" }
-- )
-- hl.bind(
--     "SUPER + ALT + 8",
--     hl.dsp.window.move({ workspace = "8", follow = false }),
--     { description = "Move Silently To Workspace 8" }
-- )
-- hl.bind(
--     "SUPER + ALT + 9",
--     hl.dsp.window.move({ workspace = "9", follow = false }),
--     { description = "Move Silently To Workspace 9" }
-- )
-- hl.bind(
--     "SUPER + ALT + 0",
--     hl.dsp.window.move({ workspace = "10", follow = false }),
--     { description = "Move Silently To Workspace 10" }
-- )


------------------------------------------------------
-- Multi MONITOR
-----------------------------------------------------

-- Each monitor gets its own "bank" of 10 workspaces, assigned left-to-right
-- by X position. SUPER+1 always means "workspace 1 on THIS monitor".
--   Monitor 0 (leftmost) → workspaces  1–10
--   Monitor 1            → workspaces 11–20
--   …etc.
--
-- The script handles all the math; these binds just pass the 1-10 slot number.
-- -------------------------------------------------------------------------------------------------

local ws_script = horizon_scripts .. "hypr/multi_monitor_workspace.sh"

-- Helper shorthand so the repeated hl.dsp.exec_cmd calls stay readable
local function ws(action, n)
    return hl.dsp.exec_cmd(ws_script .. " " .. action .. " " .. tostring(n))
end

-- ── Switch to Workspace (Context Relative) ────────────────────────────────────

hl.bind("SUPER + SHIFT + ALT + 1", ws("workspace", 1),  { description = "Switch To Context 1" })
hl.bind("SUPER + SHIFT + ALT + 2", ws("workspace", 2),  { description = "Switch To Context 2" })
hl.bind("SUPER + SHIFT + ALT + 3", ws("workspace", 3),  { description = "Switch To Context 3" })
hl.bind("SUPER + SHIFT + ALT + 4", ws("workspace", 4),  { description = "Switch To Context 4" })
hl.bind("SUPER + SHIFT + ALT + 5", ws("workspace", 5),  { description = "Switch To Context 5" })
hl.bind("SUPER + SHIFT + ALT + 6", ws("workspace", 6),  { description = "Switch To Context 6" })
hl.bind("SUPER + SHIFT + ALT + 7", ws("workspace", 7),  { description = "Switch To Context 7" })
hl.bind("SUPER + SHIFT + ALT + 8", ws("workspace", 8),  { description = "Switch To Context 8" })
hl.bind("SUPER + SHIFT + ALT + 9", ws("workspace", 9),  { description = "Switch To Context 9" })
hl.bind("SUPER + SHIFT + ALT + 0", ws("workspace", 10), { description = "Switch To Context 10" })

-- ── Move Active Window to Workspace (Context Relative) ───────────────────────

hl.bind("SUPER + 1", ws("movetoworkspace", 1),  { description = "Move To Context 1" })
hl.bind("SUPER + 2", ws("movetoworkspace", 2),  { description = "Move To Context 2" })
hl.bind("SUPER + 3", ws("movetoworkspace", 3),  { description = "Move To Context 3" })
hl.bind("SUPER + 4", ws("movetoworkspace", 4),  { description = "Move To Context 4" })
hl.bind("SUPER + 5", ws("movetoworkspace", 5),  { description = "Move To Context 5" })
hl.bind("SUPER + 6", ws("movetoworkspace", 6),  { description = "Move To Context 6" })
hl.bind("SUPER + 7", ws("movetoworkspace", 7),  { description = "Move To Context 7" })
hl.bind("SUPER + 8", ws("movetoworkspace", 8),  { description = "Move To Context 8" })
hl.bind("SUPER + 9", ws("movetoworkspace", 9),  { description = "Move To Context 9" })
hl.bind("SUPER + 0", ws("movetoworkspace", 10), { description = "Move To Context 10" })

-- ── Move Window Silently (Context Relative) ───────────────────────────────────

hl.bind("SUPER + ALT + 1", ws("movetoworkspacesilent", 1),  { description = "Silent Move To Context 1" })
hl.bind("SUPER + ALT + 2", ws("movetoworkspacesilent", 2),  { description = "Silent Move To Context 2" })
hl.bind("SUPER + ALT + 3", ws("movetoworkspacesilent", 3),  { description = "Silent Move To Context 3" })
hl.bind("SUPER + ALT + 4", ws("movetoworkspacesilent", 4),  { description = "Silent Move To Context 4" })
hl.bind("SUPER + ALT + 5", ws("movetoworkspacesilent", 5),  { description = "Silent Move To Context 5" })
hl.bind("SUPER + ALT + 6", ws("movetoworkspacesilent", 6),  { description = "Silent Move To Context 6" })
hl.bind("SUPER + ALT + 7", ws("movetoworkspacesilent", 7),  { description = "Silent Move To Context 7" })
hl.bind("SUPER + ALT + 8", ws("movetoworkspacesilent", 8),  { description = "Silent Move To Context 8" })
hl.bind("SUPER + ALT + 9", ws("movetoworkspacesilent", 9),  { description = "Silent Move To Context 9" })
hl.bind("SUPER + ALT + 0", ws("movetoworkspacesilent", 10), { description = "Silent Move To Context 10" })


-- -------------------------------------------------------------------------------------------------
-- 6. MOUSE BINDINGS
-- -------------------------------------------------------------------------------------------------

hl.bind(
    "SUPER + mouse:272",
    hl.dsp.window.drag(),
    { description = "Move Window", mouse = true }
)

hl.bind(
    "SUPER + mouse:273",
    hl.dsp.window.resize(),
    { description = "Resize Window", mouse = true }
)


-- -------------------------------------------------------------------------------------------------
-- 7. HARDWARE & MEDIA KEYS
-- -------------------------------------------------------------------------------------------------

-- Standard Media Keys (Repeatable via 'e' flag, Lockscreen bypass via 'l')
hl.bind(
    "XF86AudioRaiseVolume",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --vol-up 5"),
    { description = "Volume up", locked = true, repeating = true }
)

hl.bind(
    "XF86AudioLowerVolume",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --vol-down 5"),
    { description = "Volume down", locked = true, repeating = true }
)

hl.bind(
    "XF86AudioMute",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --vol-mute"),
    { description = "Mute", locked = true }
)

hl.bind(
    "XF86AudioMicMute",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --mic-mute"),
    { description = "Mute microphone", locked = true }
)

hl.bind(
    "XF86MonBrightnessUp",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --bright-up 5"),
    { description = "Brightness up", locked = true, repeating = true }
)

hl.bind(
    "XF86MonBrightnessDown",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --bright-down 5"),
    { description = "Brightness down", locked = true, repeating = true }
)

-- Precise Adjustments (Alt Modifier)
hl.bind(
    "ALT + XF86AudioRaiseVolume",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --vol-up 1"),
    { description = "Volume up precise", locked = true, repeating = true }
)

hl.bind(
    "ALT + XF86AudioLowerVolume",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --vol-down 1"),
    { description = "Volume down precise", locked = true, repeating = true }
)

hl.bind(
    "ALT + XF86MonBrightnessUp",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --bright-up 1"),
    { description = "Brightness up precise", locked = true, repeating = true }
)

hl.bind(
    "ALT + XF86MonBrightnessDown",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --bright-down 1"),
    { description = "Brightness down precise", locked = true, repeating = true }
)

-- Keyboard Backlight
hl.bind(
    "XF86KbdBrightnessUp",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --kbd-bright-up 10"),
    { description = "Keyboard Brightness up", locked = true, repeating = true }
)

hl.bind(
    "XF86KbdBrightnessDown",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --kbd-bright-down 10"),
    { description = "Keyboard Brightness down", locked = true, repeating = true }
)

-- Player Controls (Routed through script for OSD feedback)
hl.bind(
    "XF86AudioNext",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --next"),
    { description = "Next track", locked = true }
)

hl.bind(
    "XF86AudioPrev",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --prev"),
    { description = "Previous track", locked = true }
)

hl.bind(
    "XF86AudioPlay",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --play-pause"),
    { description = "Play", locked = true }
)

hl.bind(
    "XF86AudioPause",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --play-pause"),
    { description = "Pause", locked = true }
)

hl.bind(
    "XF86AudioStop",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --stop"),
    { description = "Stop", locked = true }
)

hl.bind(
    "SUPER + P",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --play-pause"),
    { description = "Toggle Pause", locked = true }
)

-- MPRIS module Rofi toggle
hl.bind(
    "SUPER + SHIFT + P",
    hl.dsp.exec_cmd(horizon_scripts .. "audio/mpris_toggle/mpris_playback_selection.sh"),
    { description = "Toggle Audio Active Stream" }
)

-- Custom Audio/Mic Switching Scripts
cond_bind(
    "ALT + P",
    hl.dsp.exec_cmd(horizon_scripts .. "mako_osd/osd_router/osd_router.sh --vol-mute"),
    { description = "Mute Audio", locked = true }
)

-- Mono Audio toggle
cond_bind(
    "ALT + M",
    hl.dsp.exec_cmd(horizon_scripts .. "audio/mono_audio_pipewire.py"),
    { description = "Mono Audio Toggle", locked = true }
)

-- Audio/Mic Switching
cond_bind(
    "ALT + O",
    hl.dsp.exec_cmd("pkill rofi; " .. horizon_scripts .. "audio/horizon_output.sh"),
    { description = "Switch Audio Output", locked = true }
)

cond_bind(
    "ALT + I",
    hl.dsp.exec_cmd("pkill rofi; " .. horizon_scripts .. "audio/horizon_input.sh"),
    { description = "Switch Mic Input", locked = true }
)

-- Calculator
hl.bind(
    "XF86Calculator",
    hl.dsp.exec_cmd("gnome-calculator"),
    { description = "Calculator" }
)
