-- DO NOT EDIT THIS FILE, if you want to configure something, edit the file
-- at this location: ~/.config/hypr/edit_here/source/monitors.lua
--
--
-- HOW THIS FILE IS STRUCTURED
-- ──────────────────────────────────────────────────────────────────────────
--  SECTION 1 │ GLOBAL FALLBACK RULE       (required — keep this enabled)
--  SECTION 2 │ LAPTOP BUILT-IN DISPLAY    (eDP-1 example)
--  SECTION 3 │ EXTERNAL / DESKTOP MONITORS (DP / HDMI examples)
--  SECTION 4 │ MIRROR / CLONE SETUP
--  SECTION 5 │ DISABLING A MONITOR
--  SECTION 6 │ WORKSPACE → MONITOR BINDINGS
--  SECTION 7 │ GLOBAL RENDER & POWER SETTINGS (VRR, VFR, color pipeline)
--
-- QUICK REFERENCE — hl.monitor() FIELDS
-- ──────────────────────────────────────────────────────────────────────────
--  output         STRING   Port name ("eDP-1", "DP-1", "HDMI-A-1") or ""
--                          for the global fallback.  Use `hyprctl monitors all`
--                          to list every connected and disconnected output.
--                          You may also match by description (see SECTION 3).
--
--  mode           STRING   "WIDTHxHEIGHT[@REFRESH]"  e.g. "1920x1080@144"
--                          Special values: "preferred"  (native res/rate)
--                                          "highres"    (highest resolution)
--                                          "highrr"     (highest refresh rate)
--
--  position       STRING   "XxY" pixel offset from the virtual layout origin.
--                          Hyprland uses an INVERSE-Y system:
--                            negative Y = higher on screen
--                            positive Y = lower on screen
--                          Special values: "auto"        (place to the right)
--                                          "auto-left"   "auto-right"
--                                          "auto-up"     "auto-down"
--
--  scale          NUMBER   Fractional scale factor, e.g. 1, 1.5, 2.
--                 STRING   "auto" lets Hyprland pick based on PPI.
--                          Tip: integer scales (1, 2) avoid sub-pixel blur.
--                          Valid scale = resolution / scale must be integer.
--
--  transform      NUMBER   Screen rotation / flip:
--                            0  normal              4  flipped
--                            1  90°                 5  flipped + 90°
--                            2  180°                6  flipped + 180°
--                            3  270°                7  flipped + 270°
--
--  mirror         STRING   Output name to clone this monitor from.
--                          e.g.  mirror = "eDP-1"  makes this display a copy.
--
--  disabled       BOOLEAN  true = tell Hyprland this output does not exist.
--                          Useful for phantom outputs (e.g. "Unknown-1").
--
--  bitdepth       NUMBER   8 (default) or 10 for 10-bit colour output.
--                          NOTE: Hyprland border colours do NOT support 10-bit.
--                          Some screen-capture tools also break with 10-bit.
--
--  cm             STRING   Colour management preset:
--                            "auto"     automatic (default)
--                            "sdronly"  force SDR pipeline
--                            "hdr"      HDR output (requires HDR-capable panel)
--                            "edid"     use display's EDID colour profile
--
--  sdrbrightness  NUMBER   SDR content brightness multiplier when HDR is on.
--                          Range 0.5–2.0.  Default ~1.0.
--
--  sdrsaturation  NUMBER   SDR content saturation multiplier when HDR is on.
--                          Range 0.5–1.5.  Default ~1.0.
--
--  sdr_eotf       STRING   Transfer function assumed for SDR/sRGB content:
--                            "default"  follows render.cm_sdr_eotf (global)
--                            "srgb"     piecewise sRGB
--                            "gamma22"  Gamma 2.2
--
--  icc            STRING   ABSOLUTE path to an .icm / .icc profile.
--                          Forces sdr_eotf = "srgb" automatically.
--                          Overrides the cm preset.
--                          ⚠  Incompatible with HDR gaming; artefacts may occur.
--
--  vrr            NUMBER   Variable Refresh Rate override for this monitor:
--                            0  off
--                            1  always on
--                            2  fullscreen apps only (recommended for desktops)
--                          Overrides the global misc.vrr setting.
--
--  reserved_area  NUMBER   Pixels reserved on all four edges (single value), or
--                 TABLE    a table { top=N, bottom=N, left=N, right=N }.
--                          Stacks on top of bars / layer-shells.
--                          Only ONE reserved_area rule per monitor is allowed.
-- ──────────────────────────────────────────────────────────────────────────


-- #############################################################################
-- SECTION 1 — GLOBAL FALLBACK RULE
-- #############################################################################
-- This catches any monitor that has no explicit rule below.
-- Critical for plug-and-play (projectors, docks, etc.) — do NOT remove this.
-- Change scale to 2 here if you commonly hotplug HiDPI external displays.

hl.monitor({
    output   = "",          -- "" = match any output not covered by a specific rule
    mode     = "preferred", -- use the display's advertised native resolution & rate
    position = "auto",      -- auto-place to the right of other monitors
    scale    = "auto",      -- let Hyprland decide based on PPI
})


-- #############################################################################
-- SECTION 2 — LAPTOP BUILT-IN DISPLAY (eDP-1)
-- #############################################################################
-- Uncomment and adjust the block that matches your use-case.
-- Run `hyprctl monitors all` to verify your internal display is named "eDP-1".

-- ── 2a. Standard laptop panel ─────────────────────────────────────────────
-- hl.monitor({
--     output    = "eDP-1",
--     mode      = "preferred",   -- or e.g. "2560x1600@165"
--     position  = "0x0",
--     scale     = 1,             -- use 2 for HiDPI / Retina panels
--     transform = 0,             -- 0 = normal (no rotation)
-- })

-- ── 2b. Laptop panel — 10-bit HDR (requires HDR-capable display) ───────────
-- hl.monitor({
--     output        = "eDP-1",
--     mode          = "2880x1800@90",
--     position      = "0x0",
--     scale         = 2,
--     bitdepth      = 10,        -- 10-bit colour depth
--     cm            = "hdr",     -- enable HDR colour pipeline
--     sdrbrightness = 1.0,       -- SDR content brightness in HDR mode (0.5–2.0)
--     sdrsaturation = 1.0,       -- SDR content saturation in HDR mode (0.5–1.5)
-- })

-- ── 2c. Laptop panel with ICC colour profile ───────────────────────────────
-- Absolute path required. Automatically forces sdr_eotf = "srgb".
-- hl.monitor({
--     output = "eDP-1",
--     mode   = "preferred",
--     position = "0x0",
--     scale  = 2,
--     icc    = "/home/USERNAME/.config/hypr/icc/your_panel.icm",
-- })

-- ── 2d. Laptop panel — custom SDR transfer function ───────────────────────
-- Use when you want explicit control over how sRGB content is tone-mapped.
-- hl.monitor({
--     output   = "eDP-1",
--     mode     = "preferred",
--     position = "0x0",
--     scale    = 2,
--     sdr_eotf = "srgb",         -- "default" | "srgb" | "gamma22"
-- })


-- #############################################################################
-- SECTION 3 — EXTERNAL / DESKTOP MONITORS
-- #############################################################################
-- You can match monitors by port name OR by description string.
-- Description matching is more robust (survives port changes on docks):
--   desc:MANUFACTURER MODEL SERIAL   e.g. desc:LG Electronics LG HDR 4K 0x00007B3E
-- Get the description string from:  hyprctl monitors all

-- ── 3a. Single external monitor (simple) ──────────────────────────────────
-- hl.monitor({
--     output   = "DP-1",         -- or HDMI-A-1, DP-2, etc.
--     mode     = "1920x1080@144",
--     position = "0x0",
--     scale    = 1,
-- })

-- ── 3b. Dual-monitor horizontal layout (laptop left, external right) ───────
-- Place the laptop screen at the left edge (x = 0).
-- Place the external monitor immediately to the right (x = laptop logical width).
-- If laptop is 2560px wide at scale 2, its logical width = 1280 → use "1280x0".
--
-- hl.monitor({
--     output   = "eDP-1",
--     mode     = "2560x1600@165",
--     position = "0x0",
--     scale    = 2,
-- })
-- hl.monitor({
--     output   = "DP-1",
--     mode     = "1920x1080@144",
--     position = "1280x0",       -- eDP-1 logical width (2560 / 2) = 1280
--     scale    = 1,
-- })

-- ── 3c. Triple-monitor layout (left / centre / right) ─────────────────────
-- hl.monitor({
--     output   = "DP-1",
--     mode     = "1920x1080@144",
--     position = "0x0",
--     scale    = 1,
-- })
-- hl.monitor({
--     output   = "DP-2",
--     mode     = "2560x1440@165",
--     position = "1920x0",
--     scale    = 1,
-- })
-- hl.monitor({
--     output   = "HDMI-A-1",
--     mode     = "1920x1080@60",
--     position = "4480x0",       -- 1920 + 2560
--     scale    = 1,
-- })

-- ── 3d. Vertical stack (primary on top, secondary below) ──────────────────
-- Hyprland's Y axis is inverted: positive Y goes downward on screen.
-- hl.monitor({
--     output   = "DP-1",
--     mode     = "2560x1440@165",
--     position = "0x0",
--     scale    = 1,
-- })
-- hl.monitor({
--     output   = "HDMI-A-1",
--     mode     = "1920x1080@60",
--     position = "0x1440",       -- placed directly below DP-1
--     scale    = 1,
-- })

-- ── 3e. Portrait monitor (rotated 90°) ────────────────────────────────────
-- When rotated, logical dimensions are swapped.
-- A 1080x1920 portrait monitor's logical width = 1080 → next monitor at "1080x0".
-- hl.monitor({
--     output    = "DP-3",
--     mode      = "1920x1080@60",
--     position  = "0x0",
--     scale     = 1,
--     transform = 1,             -- 1 = 90°  |  3 = 270°
-- })

-- ── 3f. 4K external with per-monitor VRR and 10-bit ───────────────────────
-- hl.monitor({
--     output   = "DP-1",
--     mode     = "3840x2160@144",
--     position = "0x0",
--     scale    = 2,
--     bitdepth = 10,
--     vrr      = 2,              -- VRR only for fullscreen apps (0=off 1=on 2=fs-only)
-- })

-- ── 3g. Match by monitor description (dock / hotplug-safe) ────────────────
-- hl.monitor({
--     output   = "desc:Dell Inc. DELL S2722DGM F9GHVJ3",
--     mode     = "2560x1440@165",
--     position = "1920x0",
--     scale    = 1,
-- })


-- #############################################################################
-- SECTION 4 — MIRROR / CLONE SETUP
-- #############################################################################
-- Mirrors duplicate another monitor's output pixel-for-pixel.
-- The `mirror` field takes the output NAME of the source display.

-- ── 4a. Mirror one specific monitor to another ────────────────────────────
-- hl.monitor({
--     output   = "HDMI-A-1",
--     mode     = "1920x1080@60",
--     position = "0x0",
--     scale    = 1,
--     mirror   = "eDP-1",        -- clone eDP-1 onto HDMI-A-1
-- })

-- ── 4b. Mirror all hotplugged monitors to the primary display ─────────────
-- (Combine with the global fallback rule in SECTION 1)
-- hl.monitor({
--     output   = "",
--     mode     = "preferred",
--     position = "auto",
--     scale    = 1,
--     mirror   = "eDP-1",        -- every unspecified output mirrors eDP-1
-- })


-- #############################################################################
-- SECTION 5 — DISABLING A MONITOR
-- #############################################################################
-- Use `disabled = true` to tell Hyprland a port does not exist.
-- This is especially useful for phantom outputs that appear on some GPUs.
-- To blank an active display temporarily, use the DPMS dispatcher instead:
--   hl.dispatch(hl.dsp.dpms({ action = "disable" }))

-- ── 5a. Suppress a phantom / ghost output ─────────────────────────────────
-- hl.monitor({
--     output   = "Unknown-1",
--     disabled = true,
-- })

-- ── 5b. Disable a known port until you need it ────────────────────────────
-- hl.monitor({
--     output   = "HDMI-A-2",
--     disabled = true,
-- })


-- #############################################################################
-- SECTION 6 — WORKSPACE → MONITOR BINDINGS
-- #############################################################################
-- Use hl.workspace_rule() to pin specific workspaces to specific monitors.
-- `monitor` accepts a port name OR a "desc:..." description string.
-- `default = true` makes that workspace the one shown when the monitor connects.

-- ── 6a. Pin individual workspaces to monitors ─────────────────────────────
-- hl.workspace_rule({ workspace = "1",  monitor = "eDP-1",   default = true })
-- hl.workspace_rule({ workspace = "2",  monitor = "eDP-1" })
-- hl.workspace_rule({ workspace = "3",  monitor = "eDP-1" })
-- hl.workspace_rule({ workspace = "4",  monitor = "eDP-1" })
-- hl.workspace_rule({ workspace = "5",  monitor = "eDP-1" })
-- hl.workspace_rule({ workspace = "6",  monitor = "DP-1",    default = true })
-- hl.workspace_rule({ workspace = "7",  monitor = "DP-1" })
-- hl.workspace_rule({ workspace = "8",  monitor = "DP-1" })
-- hl.workspace_rule({ workspace = "9",  monitor = "DP-1" })
-- hl.workspace_rule({ workspace = "10", monitor = "DP-1" })

-- ── 6b. Pin a named workspace to a monitor (by description) ───────────────
-- hl.workspace_rule({
--     workspace = "name:gaming",
--     monitor   = "desc:LG Electronics LG ULTRAGEAR 0x0000B256",
--     default   = true,
-- })

-- ── 6c. Reserved area for a specific monitor ──────────────────────────────
-- Use this when a bar/panel does not automatically reserve space,
-- or when you want extra padding on any edge.
-- hl.monitor({
--     output        = "eDP-1",
--     mode          = "preferred",
--     position      = "0x0",
--     scale         = 2,
--     reserved_area = { top = 0, bottom = 0, left = 0, right = 0 },
-- })
--
-- Or as a single integer for equal padding on all sides:
-- hl.monitor({ output = "eDP-1", reserved_area = 10 })


-- #############################################################################
-- SECTION 7 — GLOBAL RENDER & POWER SETTINGS
-- #############################################################################
-- These hl.config() options affect all monitors globally.
-- Per-monitor VRR overrides can be set with the `vrr` field in hl.monitor().

hl.config({

    misc = {
        -- ── Variable Refresh Rate (global default) ────────────────────────
        -- Overridden per-monitor by the `vrr` field in hl.monitor().
        --   0 = disabled
        --   1 = always enabled  (can cause brightness flicker on some displays)
        --   2 = fullscreen apps only  ← recommended for most users
        vrr = 0,
    },

    debug = {
        -- ── Variable Frame Rate (power saving) ───────────────────────────
        -- When true, Hyprland stops sending frames to the GPU while nothing
        -- is changing on screen.  Saves ~1 W on a laptop; looks identical.
        -- Set to false only if you notice input latency regressions.
        vfr = true,
    },

    render = {
        -- ── Global SDR EOTF (transfer function for SDR/sRGB content) ─────
        -- Applied to every monitor whose per-monitor sdr_eotf is "default".
        --   "auto"    Hyprland decides (recommended)
        --   "srgb"    piecewise sRGB curve  (best colour accuracy on most panels)
        --   "gamma22" traditional Gamma 2.2
        -- cm_sdr_eotf = "auto",

        -- ── Fullscreen HDR passthrough ────────────────────────────────────
        -- When true, fullscreen apps that output HDR signals bypass Hyprland's
        -- colour pipeline entirely for zero-overhead HDR gaming.
        -- Alternative to setting cm = "hdr" per-monitor.
        -- cm_fs_passthrough = false,

        -- ── Automatic HDR ─────────────────────────────────────────────────
        -- Experimental: automatically promote SDR content to HDR where possible.
        -- Requires --target-colorspace-hint-mode=source in mpv ≥ 0.41.
        -- cm_auto_hdr = false,
    },

})
